#!/usr/bin/env bash
# Copy static ai-harness templates to repo root with placeholder substitution
# Usage: emit-harness-scaffold.sh [--verify]
set -euo pipefail
source "$(dirname "$0")/lib/common.sh"
# shellcheck source=lib/product-meta.sh
source "$(dirname "$0")/lib/product-meta.sh"

VERIFY_ONLY=false
if [[ "${1:-}" == "--verify" ]]; then
  VERIFY_ONLY=true
fi

src="${TEMPLATES_DIR}/ai-harness"
dest="${REPO_ROOT}/ai-harness"

if [[ ! -d "$src" ]]; then
  gen_err "missing templates: $src"
  exit 1
fi

if [[ "$VERIFY_ONLY" == true ]]; then
  if [[ ! -d "$dest/scripts" ]]; then
    gen_err "ai-harness not scaffolded"
    exit 1
  fi
  for sh in "$dest/scripts"/*.sh; do
    [[ -f "$sh" ]] || continue
    if [[ ! -x "$sh" ]]; then
      gen_err "not executable: $sh"
      exit 1
    fi
  done
  harness_console="${dest}/scripts/lib/console.sh"
  if [[ ! -f "$harness_console" ]]; then
    gen_err "missing harness console: $harness_console"
    exit 1
  fi
  if ! grep -q '^aih_step()' "$harness_console" 2>/dev/null; then
    gen_err "harness console must define aih_step() — found generator console (gen_*)?"
    exit 1
  fi
  if [[ ! -f "${REPO_ROOT}/docker-compose.test.yml" ]]; then
    gen_err "missing docker-compose.test.yml"
    exit 1
  fi
  gen_ok "harness-scaffold verified"
  exit 0
fi

assert_safe_to_scaffold_harness

product_name="$(product_meta_field productName)"
[[ -z "$product_name" ]] && product_name="Product"
slug="$(product_slug)"
branch="$(branch_prefix)"
workspace="@${slug}/"

mkdir -p "$dest"

rsync -a \
  --exclude='generated/' \
  --exclude='whole-app-backlog.json' \
  --exclude='test-case-index.json' \
  --exclude='config/plan-index.json' \
  --exclude='manuals-backlog.json' \
  --exclude='manuals-index.json' \
  --exclude='state/progress.md' \
  --exclude='state/guardrails.md' \
  "$src/" "$dest/"

mkdir -p "$dest/generated/runs" "$dest/state"
echo "# Harness progress" > "${dest}/state/progress.md"
cat > "${dest}/state/guardrails.md" <<'EOF'
# Harness guardrails

Verification failures and remediation notes for harness agents.

## Doc requirements

- **Listing pages:** Collection views must implement search, filter, sort, and pagination per [14-listing-pages-search-filter-sort.md](../../docs/ui-ux/14-listing-pages-search-filter-sort.md) §0 (documented UX variants allowed). Apply `TableToolbar` and listing chrome per [design-system/tables.md](../../docs/ui-ux/design-system/tables.md).
- **Design craft:** Visual implementation via [`visual-design`](../skills/visual-design/SKILL.md) and [design-system/](../../docs/ui-ux/design-system/) modules. Authoritative index [DESIGN.md](../../docs/ui-ux/DESIGN.md); product tokens in [04-design-tokens.md](../../docs/ui-ux/04-design-tokens.md) always win for CSS values.
- **Table toolbar:** Listing routes use `TableToolbar` per [05-common-ui-components.md](../../docs/ui-ux/05-common-ui-components.md).

## Signs

- **MVP completion:** Read [integration-debt-register.md](../docs/integration-debt-register.md) and [integration-checklist.md](../docs/integration-checklist.md) before closing `mvp-completion-ready`. Run `npm run aih:verify:integration` — must pass before browser acceptance on **live** preview data.
- **No silent fixture fallback:** Do not add API-404→harness-fixture fallbacks without gating on `VITE_PREVIEW_FIXTURE_MODE`.
- **Root app wiring:** Every new backend module must be imported in the root application module in the same slice — test-only wiring in E2E harness alone is insufficient.
- **Playwright artifact hygiene:** Implementer browser screenshots must not mutate `tests/playwright-ui/test-results/` or `playwright-report/` — MCP and `npx playwright` runs update `.last-run.json`; save captures only under `ai-harness/generated/runs/screenshots/<slice-id>/implementer/`.

EOF

cat > "${dest}/test-case-index.json" <<EOF
{
  "current": [],
  "docFingerprint": null,
  "tags": {}
}
EOF

mkdir -p "${dest}/plans"
cat > "${dest}/config/plan-index.json" <<EOF
{
  "current": [],
  "docFingerprint": null,
  "tags": {}
}
EOF

cat > "${dest}/manuals-index.json" <<EOF
{
  "current": [],
  "docFingerprint": null,
  "tags": {}
}
EOF

mkdir -p "${REPO_ROOT}/docs/user-manuals/modules" "${REPO_ROOT}/docs/user-manuals/flows"
if [[ ! -f "${REPO_ROOT}/docs/user-manuals/README.md" ]]; then
  cat > "${REPO_ROOT}/docs/user-manuals/README.md" <<EOF
# ${product_name} — User Manuals

End-user guides and demo scripts generated by the AI harness ManualsGen loop.

## How to generate

From the repo root (after \`GEN_COMPLETE\` and harness planner has emitted \`ai-harness/manuals-backlog.json\`):

\`\`\`bash
npm run aih:preview          # optional — verify demo steps live
npm run aih:manualsgen:loop  # generate all module guides and demo flows
\`\`\`

See [ai-harness/docs/user-manuals-guide.md](../ai-harness/docs/user-manuals-guide.md) for details.

## Demo accounts

<!-- ManualsGen adds link to demo-accounts.md when generated -->

## Module guides

<!-- ManualsGen adds links under docs/user-manuals/modules/ -->

## Demo flows

<!-- ManualsGen adds links under docs/user-manuals/flows/ -->

## Demo runbook

<!-- ManualsGen adds link to demo-runbook.md when generated -->
EOF
fi

substitute_file() {
  substitute_all_product_placeholders "$1" "$product_name" "$slug" "$branch" "$workspace"
}

while IFS= read -r f; do
  substitute_file "$f"
done < <(find "$dest" -type f \( -name '*.md' -o -name '*.json' -o -name '*.prompt.md' -o -name '*.sh' \) 2>/dev/null)

find "$dest/scripts" -name '*.sh' -exec chmod +x {} \;

pw_src="${TEMPLATES_DIR}/tests/playwright-ui"
pw_dest="${REPO_ROOT}/tests/playwright-ui"
if [[ -d "$pw_src" ]]; then
  mkdir -p "$pw_dest"
  rsync -a "$pw_src/" "$pw_dest/"
  while IFS= read -r f; do
    substitute_file "$f"
  done < <(find "$pw_dest" -type f \( -name '*.json' -o -name '*.ts' \) 2>/dev/null)
fi

test_compose_tpl="${TEMPLATES_DIR}/docker-compose.test.yml.tpl"
if [[ -f "$test_compose_tpl" ]]; then
  cp "$test_compose_tpl" "${REPO_ROOT}/docker-compose.test.yml"
  substitute_file "${REPO_ROOT}/docker-compose.test.yml"
fi

gen_ok "harness scaffold emitted to ai-harness/"
