import { test, expect, request as playwrightRequest } from "@playwright/test";
import {
  loginPreviewInstructorViaForm,
  loginPreviewStudentViaForm,
  refreshPreviewFixtures,
} from "../src/support/auth.js";
import {
  API_BASE_URL,
  PREVIEW_CREDENTIALS,
  WEB_BASE_URL,
} from "../src/support/constants.js";

const SESSION_ACTIVE = "30000000-0000-4000-8000-000000000301";
const SESSION_CLOSED = "30000000-0000-4000-8000-000000000303";
const VALID_QR_TOKEN_ID = "40000000-0000-4000-8000-000000000403";
const CHECK_IN_COORDS = { latitude: 10.7627, longitude: 106.6602 };

/**
 * Slice: web-instructor-session-monitor
 * Source TCs: TC-AC-15-006..007, TC-AC-15-013, TC-AC-15-017,
 *   TC-FR-15-006..007, TC-FR-15-012, TC-FR-15-018,
 *   TC-NFR-08-004, TC-NFR-08-009, TC-NFR-08-013..016
 * Generated by browser test agent — do not hand-edit without re-running gate.
 */
test.describe("web-instructor-session-monitor", () => {
  test.beforeEach(async ({ page }) => {
    await refreshPreviewFixtures(page);
  });

  // TC-AC-15-006 / TC-FR-15-006 / TC-NFR-08-009
  test("active session monitor tab shows StatCards and poll status bar", async ({ page }) => {
    await page.setViewportSize({ width: 1280, height: 720 });
    await loginPreviewInstructorViaForm(page);
    await page.goto(`/sessions/sess-1?tab=monitor`);
    await expect(page.getByTestId("session-monitor-dashboard")).toBeVisible({ timeout: 15_000 });
    await expect(page.getByTestId("stat-card-present")).toBeVisible();
    await expect(page.getByTestId("stat-card-pending")).toBeVisible();
    await expect(page.getByTestId("stat-card-absent")).toBeVisible();
    await expect(page.getByTestId("monitor-poll-status")).toHaveText(/Cập nhật lúc/);
    await expect(page.getByTestId("monitor-live-summary")).toHaveText(
      /Đã điểm danh \d+ trên \d+/,
    );
  });

  // TC-AC-15-006 / TC-FR-15-006 / TC-NFR-08-004
  test("StatCards refresh within 5 seconds after student API check-in", async ({ page }) => {
    await page.setViewportSize({ width: 1280, height: 720 });
    await loginPreviewInstructorViaForm(page);
    await page.goto(`/sessions/sess-1?tab=monitor`);
    await expect(page.getByTestId("session-monitor-dashboard")).toBeVisible({ timeout: 15_000 });

    const rosterRes = await page.request.get(
      `${API_BASE_URL}/sessions/${SESSION_ACTIVE}/attendance`,
    );
    expect(rosterRes.ok()).toBeTruthy();
    const roster = (await rosterRes.json()) as {
      records: Array<{ id: string; institutionalId: string; status: string }>;
    };
    const target =
      roster.records.find((record) => record.institutionalId === "SV2026001") ??
      roster.records[0];
    expect(target).toBeTruthy();
    const presentCard = page.getByTestId("stat-card-present").locator("p.font-display");
    const initialPresent = Number(
      (await presentCard.innerText()).split("/")[0]?.trim() ?? "0",
    );

    if (target!.status === "Present") {
      const prep = await page.request.patch(`${API_BASE_URL}/attendance/${target!.id}`, {
        data: { status: "Absent", note: "Chuẩn bị kiểm thử monitor poll" },
      });
      expect(prep.ok()).toBeTruthy();
      await expect
        .poll(
          async () => Number((await presentCard.innerText()).split("/")[0]?.trim() ?? "0"),
          { timeout: 6_500, intervals: [500] },
        )
        .toBe(initialPresent - 1);
    }

    const baselinePresent = Number(
      (await presentCard.innerText()).split("/")[0]?.trim() ?? "0",
    );

    const studentApi = await playwrightRequest.newContext();
    const studentLogin = await studentApi.post(`${API_BASE_URL}/auth/login`, {
      data: PREVIEW_CREDENTIALS.student,
    });
    expect(studentLogin.ok()).toBeTruthy();

    const t0 = Date.now();
    const checkIn = await studentApi.post(`${API_BASE_URL}/check-in`, {
      data: { tokenId: VALID_QR_TOKEN_ID, ...CHECK_IN_COORDS },
    });
    const checkInBody = (await checkIn.json()) as { outcome: string };
    expect(checkIn.ok()).toBeTruthy();
    expect(checkInBody.outcome).toBe("Success");
    await studentApi.dispose();

    await expect
      .poll(
        async () => Number((await presentCard.innerText()).split("/")[0]?.trim() ?? "0"),
        { timeout: 6_500, intervals: [250] },
      )
      .toBe(baselinePresent + 1);

    expect(Date.now() - t0).toBeLessThanOrEqual(6_500);
    await expect(
      page.getByTestId(`monitor-row-${target!.institutionalId.toLowerCase()}`),
    ).toContainText("Có mặt");
    await expect(page.getByTestId("monitor-poll-status")).toHaveText(/Cập nhật lúc/);
  });

  // TC-AC-15-007 / TC-FR-15-007
  test("monitor roster sorts by Trạng thái ascending", async ({ page }) => {
    await page.setViewportSize({ width: 1280, height: 720 });
    await loginPreviewInstructorViaForm(page);
    await page.goto(`/sessions/sess-1?tab=monitor`);
    await expect(page.getByTestId("session-monitor-dashboard")).toBeVisible({ timeout: 15_000 });
    await page.getByTestId("monitor-sort-status").click();
    await expect(page.getByTestId("monitor-sort-status")).toHaveAttribute("aria-sort", "ascending");

    const statuses = await page.locator('[data-testid^="monitor-row-"] td:nth-child(3)').allInnerTexts();
    const orderIndex = (label: string) => {
      if (label.includes("Chưa điểm danh") || label.includes("Chờ")) return 0;
      if (label.includes("Vắng")) return 1;
      if (label.includes("Có mặt")) return 2;
      if (label.includes("Có phép")) return 3;
      return 99;
    };
    const indices = statuses.map((s) => orderIndex(s.trim()));
    expect(indices).toEqual([...indices].sort((a, b) => a - b));
  });

  // TC-AC-15-013 / TC-FR-15-012
  test("monitor toolbar filters roster while StatCards keep totals", async ({ page }) => {
    await page.setViewportSize({ width: 1280, height: 720 });
    await loginPreviewInstructorViaForm(page);
    await page.goto(`/sessions/sess-1?tab=monitor`);
    await expect(page.getByTestId("monitor-roster-toolbar")).toBeVisible({ timeout: 15_000 });

    const presentCountBefore = await page
      .getByTestId("stat-card-present")
      .locator("p.font-display")
      .innerText();

    await page.getByTestId("monitor-status-filter").selectOption("Present");
    await expect(page.locator('[data-testid^="monitor-row-"]')).not.toHaveCount(0);
    for (const row of await page.locator('[data-testid^="monitor-row-"]').all()) {
      await expect(row).toContainText("Có mặt");
    }
    await expect(page.getByTestId("stat-card-present").locator("p.font-display")).toHaveText(
      presentCountBefore,
    );

    await page.getByTestId("monitor-status-filter").selectOption("all");
    await expect(page.locator('[data-testid^="monitor-row-"]')).not.toHaveCount(0);

    await page.getByTestId("monitor-student-search").fill("Nguyễn");
    await expect(page.locator('[data-testid^="monitor-row-"]')).toHaveCount(1);
    await page.getByTestId("monitor-search-clear").click();
    await page.getByTestId("monitor-student-search").fill("SV2026001");
    await expect(page.getByTestId("monitor-row-sv2026001")).toBeVisible();
    await expect(page.getByTestId("stat-card-present").locator("p.font-display")).toHaveText(
      presentCountBefore,
    );
  });

  // TC-NFR-08-009
  test("monitor auto-polls on active session and stops on closed session", async ({ page }) => {
    await page.setViewportSize({ width: 1280, height: 720 });
    await loginPreviewInstructorViaForm(page);
    await page.goto(`/sessions/sess-1?tab=monitor`);
    await expect(page.getByTestId("monitor-poll-status")).toHaveText(/Cập nhật lúc/, {
      timeout: 15_000,
    });

    const firstPoll = await page.getByTestId("monitor-poll-status").innerText();
    await page.waitForTimeout(5_500);
    const secondPoll = await page.getByTestId("monitor-poll-status").innerText();
    expect(secondPoll).not.toBe(firstPoll);

    const closedRequests: string[] = [];
    page.on("request", (req) => {
      if (req.url().includes("/attendance")) closedRequests.push(req.url());
    });
    await page.goto(`/sessions/${SESSION_CLOSED}/monitor`);
    await expect(page.getByRole("alert").filter({ hasText: "Buổi học đã kết thúc" })).toBeVisible();
    const countAfterLoad = closedRequests.length;
    await page.waitForTimeout(10_000);
    expect(closedRequests.length).toBeLessThanOrEqual(countAfterLoad + 1);
  });

  // TC-NFR-08-013
  test("monitor recovers after transient attendance poll failure", async ({ page }) => {
    await page.setViewportSize({ width: 1280, height: 720 });
    await loginPreviewInstructorViaForm(page);
    await page.goto(`/sessions/sess-1?tab=monitor`);
    await expect(page.getByTestId("session-monitor-dashboard")).toBeVisible({ timeout: 15_000 });

    let failOnce = true;
    await page.route("**/api/v1/sessions/**/attendance", async (route) => {
      if (failOnce) {
        failOnce = false;
        await route.fulfill({
          status: 503,
          body: JSON.stringify({ errorCode: "ServiceUnavailable", message: "temp" }),
        });
      } else {
        await route.continue();
      }
    });

    await page.waitForTimeout(6_000);
    await expect(page.getByTestId("monitor-poll-status")).toContainText("Không thể cập nhật");
    await page.getByRole("button", { name: /thử lại/i }).click();
    await expect(page.getByTestId("monitor-poll-status")).toHaveText(/Cập nhật lúc/, {
      timeout: 10_000,
    });
    expect(page.url()).toContain("/sessions/sess-1");
  });

  // TC-NFR-08-015
  test("instructor monitor layout omits admin nav and student routes", async ({ page }) => {
    await page.setViewportSize({ width: 1280, height: 720 });
    await loginPreviewInstructorViaForm(page);
    await page.goto(`/sessions/sess-1?tab=monitor`);
    await expect(page.getByTestId("session-monitor-dashboard")).toBeVisible({ timeout: 15_000 });

    await expect(page.locator('a[href*="/admin"]')).toHaveCount(0);
    await expect(page.getByRole("navigation", { name: /giảng viên/i })).toBeVisible();
    await expect(page.getByRole("link", { name: "Buổi học" })).toBeVisible();
    await expect(page.getByRole("link", { name: "Báo cáo" })).toBeVisible();
    await expect(page.getByTestId("student-bottom-nav")).toHaveCount(0);
    await expect(page.locator('a[href="/check-in"]')).toHaveCount(0);
  });

  // TC-NFR-08-016
  test("student mobile BottomNav shows only check-in and history", async ({ page }) => {
    await page.setViewportSize({ width: 375, height: 667 });
    await loginPreviewStudentViaForm(page);
    await page.goto(`${WEB_BASE_URL}/check-in`);
    await expect(page.getByTestId("student-bottom-nav")).toBeVisible({ timeout: 15_000 });

    const navLinks = page.getByTestId("student-bottom-nav").getByRole("link");
    await expect(navLinks).toHaveCount(2);
    await expect(navLinks.filter({ hasText: "Điểm danh" })).toHaveAttribute("href", "/check-in");
    await expect(navLinks.filter({ hasText: "Lịch sử" })).toHaveAttribute("href", "/history");
    await expect(page.locator('a[href*="/admin"], a[href*="/sessions"], a[href*="/reports"]')).toHaveCount(
      0,
    );

    await page.goto(`${WEB_BASE_URL}/history`);
    await expect(
      page.getByTestId("student-bottom-nav").getByRole("link", { name: "Lịch sử" }),
    ).toHaveAttribute("aria-current", "page");
  });

  test("dedicated /sessions/:id/monitor route renders monitor page", async ({ page }) => {
    await page.setViewportSize({ width: 1280, height: 720 });
    await loginPreviewInstructorViaForm(page);
    await page.goto(`/sessions/${SESSION_ACTIVE}/monitor`);
    await expect(page.getByTestId("session-monitor-page")).toBeVisible({ timeout: 15_000 });
    await expect(page.getByTestId("session-monitor-dashboard")).toBeVisible();
    await expect(page.getByRole("heading", { name: /Theo dõi/i })).toBeVisible();
  });

  test("closed session monitor shows ended banner and finalized roster", async ({ page }) => {
    await page.setViewportSize({ width: 1280, height: 720 });
    await loginPreviewInstructorViaForm(page);
    await page.goto(`/sessions/${SESSION_CLOSED}/monitor`);
    await expect(page.getByTestId("session-monitor-page")).toBeVisible({ timeout: 15_000 });
    await expect(page.getByRole("alert").filter({ hasText: "Buổi học đã kết thúc" })).toBeVisible();
    await expect(page.getByTestId("session-monitor-dashboard")).toBeVisible();
    await expect(page.locator('[data-testid^="monitor-row-"]')).not.toHaveCount(0);
  });
});
