import { writeFileSync } from "node:fs";
import { join } from "node:path";
import { tmpdir } from "node:os";
import { test, expect } from "@playwright/test";
import {
  loginPreviewAdminViaForm,
  loginPreviewStudentViaForm,
  loginPreviewInstructorViaForm,
  loginViaForm,
  refreshPreviewFixtures,
} from "../src/support/auth.js";
import { WEB_BASE_URL } from "../src/support/constants.js";

/**
 * Slice: web-admin-users
 * Source TCs: TC-AC-01-009..011, TC-AC-01-017..018, TC-FR-01-009..011, TC-FR-01-016,
 *   TC-FR-01-024, TC-NFR-11-017..019, TC-NFR-11-021..022
 * Generated by browser test agent — do not hand-edit without re-running gate.
 */
test.describe("web-admin-users", () => {
  test.beforeEach(async ({ page }) => {
    await refreshPreviewFixtures(page);
  });

  // TC-AC-01-009 / TC-FR-01-009
  test("admin creates student via UserForm and sees active badge in list", async ({ page }) => {
    await loginPreviewAdminViaForm(page);
    await page.goto(`${WEB_BASE_URL}/admin/users`);

    const uniqueId = `SV2026${Date.now().toString().slice(-4)}`;
    const email = `pw-ui-${Date.now()}@example.edu.vn`;
    const displayName = `PW UI Student ${uniqueId}`;

    await page.getByTestId("create-user-link").click();
    await page.getByRole("textbox", { name: "Mã SV / Mã cán bộ" }).fill(uniqueId);
    await page.getByRole("textbox", { name: "Họ và tên" }).fill(displayName);
    await page.getByRole("textbox", { name: "Email" }).fill(email);
    await page.getByRole("textbox", { name: "Mật khẩu" }).fill("TestPass123");
    await page.getByRole("combobox", { name: "Vai trò" }).selectOption({ label: "Sinh viên" });
    await page.getByTestId("user-form-submit").click();

    await expect(page).toHaveURL(/\/admin\/users$/);
    const row = page.getByTestId(`user-row-${uniqueId}`);
    await expect(row).toBeVisible({ timeout: 15_000 });
    await expect(row.getByTestId("user-active-badge")).toHaveText("Đang hoạt động");
    await expect(row.getByText(email)).toBeVisible();
  });

  // TC-AC-01-010 / TC-FR-01-010
  test("duplicate institutionalId shows inline field error and keeps form open", async ({
    page,
  }) => {
    await loginPreviewAdminViaForm(page);
    await page.goto(`${WEB_BASE_URL}/admin/users/new`);

    await page.getByRole("textbox", { name: "Mã SV / Mã cán bộ" }).fill("SV2026001");
    await page.getByRole("textbox", { name: "Họ và tên" }).fill("Duplicate Test");
    await page.getByRole("textbox", { name: "Email" }).fill("duplicate-pw-ui@example.edu.vn");
    await page.getByRole("textbox", { name: "Mật khẩu" }).fill("TestPass123");
    await page.getByTestId("user-form-submit").click();

    await expect(page).toHaveURL(/\/admin\/users\/new$/);
    await expect(page.getByText(/Mã định danh đã tồn tại/i)).toBeVisible();
    await expect(page.getByTestId("user-form")).toBeVisible();
  });

  // TC-AC-01-011 / TC-FR-01-011
  test("deactivated student sees localized login error", async ({ page }) => {
    await page.goto(`${WEB_BASE_URL}/login`);
    await loginViaForm(page, "deactivated@example.edu.vn", "StudentPass8");

    await expect(page).toHaveURL(/\/login$/);
    await expect(page.getByRole("alert")).toHaveText(/Tài khoản đã bị vô hiệu hóa/i);
  });

  // TC-AC-01-017 / TC-FR-01-024
  test("CSV import shows preview with create/update rows then import summary", async ({
    page,
  }) => {
    await loginPreviewAdminViaForm(page);
    await page.goto(`${WEB_BASE_URL}/admin/users/import`);

    const uniqueId = `SV2026${Date.now().toString().slice(-4)}`;
    const csvPath = join(tmpdir(), `user-import-${Date.now()}.csv`);
    writeFileSync(
      csvPath,
      [
        "institutional_id,display_name,email,role,active",
        `${uniqueId},Import PW New,import-pw-new-${Date.now()}@example.edu.vn,Student,true`,
        "SV2026001,Import PW Updated,student@example.edu.vn,Student,true",
      ].join("\n"),
      "utf8",
    );

    await page.getByTestId("user-import-file-select").setInputFiles(csvPath);
    await page.getByRole("button", { name: /xem trước/i }).click();

    await expect(page.getByRole("cell", { name: "Cập nhật" })).toBeVisible();
    await expect(page.getByRole("cell", { name: "Tạo mới" })).toHaveCount(1);

    await page.getByRole("button", { name: /xác nhận nhập/i }).click();
    await expect(page.getByText(/Hoàn tất nhập/i)).toBeVisible({ timeout: 15_000 });
    await expect(page.getByText(/Đã tạo 1, cập nhật 1/i)).toBeVisible();
  });

  // TC-AC-01-018 (search + filters subset)
  test("user list search syncs q param and role filter shows removable chip", async ({
    page,
  }) => {
    await loginPreviewAdminViaForm(page);
    await page.goto(`${WEB_BASE_URL}/admin/users`);

    await page.getByTestId("user-list-search").fill("SV2026001");
    await expect(page).toHaveURL(/[?&]q=SV2026001/, { timeout: 5_000 });
    await expect(page.getByTestId("user-row-SV2026001")).toBeVisible();

    await page.getByTestId("user-search-clear").click();
    await page.getByTestId("user-role-filter").selectOption("Student");
    await expect(page.getByTestId("user-filter-chip-role")).toBeVisible({ timeout: 5_000 });
    await expect(page.getByTestId("user-row-GV2026001")).not.toBeVisible();
    await expect(page.getByTestId("user-row-SV2026001")).toBeVisible();
  });

  // TC-FR-01-016 — use an isolated user so parallel monitor gates keep SV2026001 enrolled
  test("admin deactivates user and inactive badge appears in table", async ({ page }) => {
    await loginPreviewAdminViaForm(page);

    const uniqueId = `SV2026${Date.now().toString().slice(-4)}`;
    const email = `deact-pw-${Date.now()}@example.edu.vn`;

    await page.goto(`${WEB_BASE_URL}/admin/users/new`);
    await page.getByRole("textbox", { name: "Mã SV / Mã cán bộ" }).fill(uniqueId);
    await page.getByRole("textbox", { name: "Họ và tên" }).fill(`Deactivate ${uniqueId}`);
    await page.getByRole("textbox", { name: "Email" }).fill(email);
    await page.getByRole("textbox", { name: "Mật khẩu" }).fill("TestPass123");
    await page.getByRole("combobox", { name: "Vai trò" }).selectOption({ label: "Sinh viên" });
    await page.getByTestId("user-form-submit").click();
    await expect(page).toHaveURL(/\/admin\/users$/);

    await page.getByTestId(`deactivate-user-${uniqueId}`).click();
    await expect(page.getByTestId("deactivate-user-dialog")).toBeVisible();
    await page.getByTestId("confirm-dialog-accept").click();

    const row = page.getByTestId(`user-row-${uniqueId}`);
    await expect(row.getByTestId("user-inactive-badge")).toHaveText("Đã vô hiệu hóa", {
      timeout: 10_000,
    });
    await expect(page.getByTestId(`deactivate-user-${uniqueId}`)).not.toBeVisible();
  });

  // TC-NFR-11-018
  test("student direct admin users URL shows ForbiddenPage without roster data", async ({
    page,
  }) => {
    await loginPreviewStudentViaForm(page);

    const forbiddenLinks = await page.evaluate(() =>
      Array.from(document.querySelectorAll("a[href]"))
        .map((a) => a.getAttribute("href"))
        .filter((href) => href?.startsWith("/admin") || href === "/sessions" || href === "/reports"),
    );
    expect(forbiddenLinks).toEqual([]);

    await page.goto(`${WEB_BASE_URL}/admin/users`);
    await expect(page.getByRole("heading", { name: /Không có quyền truy cập/i })).toBeVisible();
    await expect(page.getByTestId("user-list-table")).not.toBeVisible();
    await expect(page.getByTestId("admin-users-page")).not.toBeVisible();
  });

  // TC-NFR-11-019 — instructor scoped inline export lives in web-instructor-reports slice
  // TC-NFR-11-019 (admin institution-wide export)
  test("admin export page downloads CSV after filter apply and confirm", async ({ page }) => {
    await loginPreviewAdminViaForm(page);
    await page.goto(`${WEB_BASE_URL}/admin/export`);

    await page.getByLabel("Từ ngày").fill("2026-06-01");
    await page.getByLabel("Đến ngày").fill("2026-06-30");
    await page.getByRole("button", { name: "Áp dụng" }).click();

    await expect(page.getByRole("button", { name: /xuất csv/i })).toBeVisible({ timeout: 10_000 });

    const downloadPromise = page.waitForEvent("download");
    await page.getByRole("button", { name: /xuất csv/i }).click();
    await page
      .getByRole("alertdialog", { name: /xác nhận xuất csv/i })
      .getByRole("button", { name: /xuất csv/i })
      .click();
    const download = await downloadPromise;
    expect(download.suggestedFilename()).toMatch(/\.csv$/);
  });

  // TC-NFR-11-021 / TC-NFR-11-022 (instructor nav negative matrix)
  test("instructor layout omits all admin nav links from sidebar", async ({ page }) => {
    await loginPreviewInstructorViaForm(page);
    await page.goto(`${WEB_BASE_URL}/sessions`);

    const adminLinkCount = await page.evaluate(
      () => document.querySelectorAll('a[href^="/admin"]').length,
    );
    expect(adminLinkCount).toBe(0);

    const sidebarItems = await page.evaluate(() =>
      Array.from(document.querySelectorAll("aside nav a")).map((a) => ({
        href: a.getAttribute("href"),
        text: a.textContent?.trim(),
      })),
    );
    expect(sidebarItems.map((i) => i.text)).toEqual(["Buổi học", "Báo cáo"]);
    await expect(page.getByTestId("bottom-nav")).not.toBeVisible();

    await page.goto(`${WEB_BASE_URL}/admin/export`);
    await expect(page.getByRole("heading", { name: /Không có quyền truy cập/i })).toBeVisible();
  });
});
