import { test, expect } from "@playwright/test";
import {
  assertUnauthenticated,
  loginPreviewAdminViaForm,
  loginPreviewInstructorViaForm,
  loginPreviewStudentViaForm,
  loginViaForm,
  logoutViaUserMenu,
  previewExpireSession,
  gotoExpectingRedirect,
} from "../src/support/auth.js";
import {
  PREVIEW_CREDENTIALS,
  PREVIEW_TOKEN_ALIASES,
  WEB_BASE_URL,
} from "../src/support/constants.js";

/**
 * Slice: web-auth-login
 * Source TCs: TC-AC-02-011..016, TC-FR-02-017..026, TC-BR-06-016..022, TC-NFR-16-013..015
 * Generated by browser test agent — do not hand-edit without re-running gate.
 */
test.describe("web-auth-login", () => {
  test.beforeEach(async ({ context }) => {
    await context.clearCookies();
  });

  // TC-AC-02-011 / TC-FR-02-017 / TC-BR-06-016
  test("unauthenticated check-in deep link redirects to login preserving returnUrl", async ({
    page,
  }) => {
    await page.setViewportSize({ width: 375, height: 667 });
    await page.goto(`/check-in?token=${PREVIEW_TOKEN_ALIASES.stale}`);
    await expect(page).toHaveURL(/\/login\?returnUrl=%2Fcheck-in%3Ftoken%3Dstale-token-id/);
    await expect(page.getByRole("heading", { name: /^đăng nhập$/i })).toBeVisible();
    await expect(page.getByRole("button", { name: /^đăng nhập$/i })).toBeVisible();
  });

  // TC-AC-02-012 / TC-FR-02-018 / TC-BR-06-017
  test("successful login after redirect returns student to check-in flow", async ({ page }) => {
    await page.setViewportSize({ width: 375, height: 667 });
    await page.goto(`/check-in?token=${PREVIEW_TOKEN_ALIASES.stale}`);
    await expect(page).toHaveURL(/returnUrl=/);
    await loginPreviewStudentViaForm(page);
    await expect(page).toHaveURL(new RegExp(`/check-in\\?token=${PREVIEW_TOKEN_ALIASES.stale}`));
    await expect(page.getByTestId("user-menu-trigger")).toBeVisible();
  });

  // TC-AC-02-013 / TC-FR-02-019 / TC-BR-06-018
  test("expired session on check-in submit shows alert and redirects to login", async ({
    page,
  }) => {
    await page.setViewportSize({ width: 375, height: 667 });
    await page.goto("/login");
    await loginPreviewStudentViaForm(page);
    await page.goto(`/check-in?token=${PREVIEW_TOKEN_ALIASES.valid}&expireSessionOnSubmit=1`);
    await expect(page.getByTestId("check-in-submit")).toBeVisible({ timeout: 15_000 });
    await page.getByTestId("check-in-submit").click();
    await expect(page).toHaveURL(/sessionExpired=1/);
    await expect(page.getByTestId("login-session-expired")).toHaveText(
      /phiên đăng nhập đã hết hạn/i,
    );
  });

  // TC-FR-02-020
  test("login form displays localized error on invalid credentials", async ({ page }) => {
    await page.goto("/login");
    const { email } = PREVIEW_CREDENTIALS.student;
    await loginViaForm(page, email, "wrongpassword");
    await expect(page).toHaveURL(/\/login$/);
    await expect(page.getByRole("alert")).toHaveText(/email hoặc mật khẩu không đúng/i);
  });

  // TC-FR-02-021
  test("role-based redirect after login sends each role to correct home", async ({ page }) => {
    await page.goto("/login");
    await loginPreviewStudentViaForm(page);
    await expect(page).toHaveURL(/\/check-in/);

    await page.context().clearCookies();
    await page.goto("/login");
    await loginPreviewInstructorViaForm(page);
    await expect(page).toHaveURL(/\/sessions/);

    await page.context().clearCookies();
    await page.goto("/login");
    await loginPreviewAdminViaForm(page);
    await expect(page).toHaveURL(/\/admin/);
  });

  // TC-BR-06-019
  test("protected instructor route redirects unauthenticated user to login", async ({ page }) => {
    await page.goto("/sessions");
    await expect(page).toHaveURL(/\/login\?returnUrl=%2Fsessions/);
    await expect(page.getByRole("heading", { name: /^đăng nhập$/i })).toBeVisible();
  });

  // TC-NFR-16-013
  test("expired session on check-in deep link blocks preflight and redirects to login", async ({
    page,
  }) => {
    await page.setViewportSize({ width: 375, height: 667 });
    await page.goto("/login");
    await loginPreviewStudentViaForm(page);
    await previewExpireSession(page);
    await gotoExpectingRedirect(
      page,
      `/check-in?token=${PREVIEW_TOKEN_ALIASES.valid}`,
      /sessionExpired=1/,
    );
    await expect(page.getByTestId("login-session-expired")).toBeVisible();
    await expect(page.getByTestId("check-in-submit")).not.toBeVisible();
  });

  // TC-NFR-16-014
  test("protected instructor route redirects expired session to login", async ({ page }) => {
    await page.goto("/login");
    await loginPreviewInstructorViaForm(page);
    await previewExpireSession(page);
    await gotoExpectingRedirect(
      page,
      "/sessions",
      /\/login\?returnUrl=%2Fsessions&sessionExpired=1/,
    );
    await expect(page.getByTestId("login-session-expired")).toBeVisible();
  });

  // TC-NFR-16-015
  test("re-login after session expiry returns user to preserved check-in deep link", async ({
    page,
  }) => {
    await page.goto(
      `/login?returnUrl=%2Fcheck-in%3Ftoken%3D${PREVIEW_TOKEN_ALIASES.valid}&sessionExpired=1`,
    );
    await expect(page.getByTestId("login-session-expired")).toBeVisible();
    await loginPreviewStudentViaForm(page);
    await expect(page).toHaveURL(
      new RegExp(`/check-in\\?token=${PREVIEW_TOKEN_ALIASES.valid}`),
    );
  });

  // TC-AC-02-015 / TC-FR-02-025 / TC-BR-06-022
  test("user menu logout from student shell clears session and blocks protected routes", async ({
    page,
  }) => {
    await page.goto("/login");
    await loginPreviewStudentViaForm(page);
    await expect(page).toHaveURL(/\/check-in/);
    await logoutViaUserMenu(page);
    await expect(page).toHaveURL(/\/login$/);
    await assertUnauthenticated(page);
    await page.goto("/sessions");
    await expect(page).toHaveURL(/\/login\?returnUrl=%2Fsessions/);
  });

  test("user menu logout from instructor and admin shells lands on login without returnUrl", async ({
    page,
  }) => {
    await page.goto("/login");
    await loginPreviewInstructorViaForm(page);
    await expect(page).toHaveURL(/\/sessions/);
    await logoutViaUserMenu(page);
    await expect(page).toHaveURL(/\/login$/);
    await assertUnauthenticated(page);

    await page.context().clearCookies();
    await page.goto("/login");
    await loginPreviewAdminViaForm(page);
    await expect(page).toHaveURL(/\/admin/);
    await logoutViaUserMenu(page);
    await expect(page).toHaveURL(/\/login$/);
    await assertUnauthenticated(page);
    await page.goto("/admin/users");
    await expect(page).toHaveURL(/\/login\?returnUrl=%2Fadmin%2Fusers/);
  });

  // TC-AC-02-016 / TC-FR-02-026
  test("user menu identity panel shows profile fields from auth/me", async ({ page }) => {
    await page.goto("/login");
    await loginPreviewStudentViaForm(page);
    await page.getByTestId("user-menu-trigger").click();
    const panel = page.locator("[data-radix-menu-content]");
    await expect(panel.getByText("Sinh viên Nguyễn Văn A")).toBeVisible();
    await expect(panel.getByText("student@example.edu.vn")).toBeVisible();
    await expect(panel.getByText(/mã:\s*sv2026001/i)).toBeVisible();
    await expect(panel.getByText(/^sinh viên$/i)).toBeVisible();
    await expect(page.getByTestId("user-menu-logout")).toBeVisible();
  });
});
