import { test, expect } from "@playwright/test";
import {
  loginPreviewInstructorViaForm,
  loginPreviewStudentViaForm,
  refreshPreviewFixtures,
} from "../src/support/auth.js";
import {
  PREVIEW_CREDENTIALS,
  PREVIEW_TOKEN_ALIASES,
  WEB_BASE_URL,
} from "../src/support/constants.js";

const SESSION_ACTIVE = "30000000-0000-4000-8000-000000000301";
const SESSION_DRAFT = "30000000-0000-4000-8000-000000000302";
const SESSION_CLOSED = "30000000-0000-4000-8000-000000000303";

/**
 * Slice: web-instructor-qr-display
 * Source TCs: TC-AC-06-017..021, TC-FR-06-018..021, TC-FR-06-025,
 *   TC-NFR-06-013..016, TC-NFR-06-020, TC-NFR-20-009..015
 * Generated by browser test agent — do not hand-edit without re-running gate.
 */
test.describe("web-instructor-qr-display", () => {
  test.beforeEach(async ({ page }) => {
    await refreshPreviewFixtures(page);
  });

  // TC-AC-06-017 / TC-FR-06-018 / TC-NFR-06-013
  test("active session QR tab shows scannable code and decrementing countdown", async ({
    page,
  }) => {
    await loginPreviewInstructorViaForm(page);
    await page.goto(`/sessions/${SESSION_ACTIVE}?tab=qr`);
    await expect(page.getByTestId("qr-display-panel")).toBeVisible();
    await expect(page.getByTestId("qr-code-image")).toBeVisible();
    const countdown = page.getByTestId("qr-countdown");
    await expect(countdown).toContainText(/Mã mới sau \d+ giây/);
    const first = Number(await countdown.getAttribute("data-seconds-remaining"));
    expect(first).toBeGreaterThanOrEqual(1);
    expect(first).toBeLessThanOrEqual(30);
    await page.waitForTimeout(1100);
    const second = Number(await countdown.getAttribute("data-seconds-remaining"));
    expect(second).toBe(first - 1);
    await expect(page.getByTestId("qr-present-link")).toHaveAttribute(
      "href",
      `/sessions/${SESSION_ACTIVE}/qr-present`,
    );
  });

  // TC-AC-06-018 / TC-FR-06-019 / TC-NFR-20-009
  test("fullscreen qr-present renders large inverse QR with countdown and exit", async ({
    page,
  }) => {
    await page.setViewportSize({ width: 1280, height: 720 });
    await loginPreviewInstructorViaForm(page);
    await page.goto(`/sessions/${SESSION_ACTIVE}/qr-present`);
    await expect(page.getByTestId("qr-present-page")).toBeVisible();
    await expect(page.getByTestId("qr-code-image")).toBeVisible();
    await expect(page.getByTestId("qr-countdown")).toContainText(/Mã mới sau/);
    await expect(page.getByText("Quét mã để điểm danh")).toBeVisible();
    await expect(page.getByTestId("status-badge-Active")).toBeVisible();
    const qrBox = await page.getByTestId("qr-code-image").boundingBox();
    expect(qrBox?.width ?? 0).toBeGreaterThanOrEqual(280);
    await expect(page.getByTestId("qr-present-page")).toHaveCSS(
      "background-color",
      "rgb(0, 0, 0)",
    );
    await page.getByTestId("qr-exit-fullscreen").click();
    await expect(page).toHaveURL(new RegExp(`/sessions/${SESSION_ACTIVE}\\?tab=qr`));
    await expect(page.getByTestId("qr-display-panel")).toBeVisible();
  });

  // TC-NFR-20-010 / TC-NFR-20-011
  test("fullscreen countdown uses presentation typography and warning accent at 10s", async ({
    page,
  }) => {
    await page.setViewportSize({ width: 1280, height: 720 });
    await loginPreviewInstructorViaForm(page);
    await page.goto(`/sessions/${SESSION_ACTIVE}/qr-present`);
    const countdown = page.getByTestId("qr-countdown");
    await expect(countdown).toBeVisible();
    const accentStyles = await countdown.evaluate((el) => {
      const s = getComputedStyle(el);
      return { fontSize: s.fontSize, fontWeight: s.fontWeight, color: s.color };
    });
    expect(Number.parseFloat(accentStyles.fontSize)).toBeGreaterThanOrEqual(48);
    expect(Number(accentStyles.fontWeight)).toBeGreaterThanOrEqual(700);
    for (let i = 0; i < 25; i++) {
      const secs = Number(await countdown.getAttribute("data-seconds-remaining"));
      if (secs <= 10) break;
      await page.waitForTimeout(500);
    }
    const warningColor = await countdown.evaluate((el) => getComputedStyle(el).color);
    expect(warningColor).toBe("rgb(250, 204, 21)");
  });

  // TC-AC-06-019 / TC-FR-06-020 / TC-NFR-06-020
  test("draft and closed sessions show session-not-active without QR", async ({ page }) => {
    await loginPreviewInstructorViaForm(page);
    await page.goto(`/sessions/${SESSION_DRAFT}?tab=qr`);
    await expect(page.getByTestId("session-not-active")).toContainText("Buổi học chưa mở");
    await expect(page.getByTestId("qr-code-image")).toHaveCount(0);
    await expect(page.getByTestId("qr-countdown")).toHaveCount(0);
    await page.goto(`/sessions/${SESSION_CLOSED}?tab=qr`);
    await expect(page.getByTestId("session-not-active")).toContainText("Buổi học đã kết thúc");
    await expect(page.getByTestId("qr-code-image")).toHaveCount(0);
    await expect(page.getByTestId("qr-present-link")).toHaveCount(0);
  });

  // TC-AC-06-020 / TC-FR-06-021
  test("student stale token shows ExpiredQr outcome with Quét lại recovery", async ({
    page,
  }) => {
    await page.setViewportSize({ width: 375, height: 812 });
    await loginPreviewStudentViaForm(page);
    await page.goto(`/check-in?token=${PREVIEW_TOKEN_ALIASES.stale}`);
    await expect(page.getByTestId("check-in-outcome-ExpiredQr")).toBeVisible();
    await expect(page.getByTestId("check-in-outcome-ExpiredQr")).toContainText(
      "Mã QR đã hết hạn, vui lòng quét mã mới",
    );
    await expect(page.getByTestId("gps-capture-step")).toHaveCount(0);
    await page.getByRole("button", { name: /quét lại/i }).click();
    await expect(page).toHaveURL(/\/check-in/);
  });

  // TC-FR-06-025
  test("valid token preflight reaches GPS ready without spinner", async ({ page }) => {
    await page.setViewportSize({ width: 375, height: 812 });
    await loginPreviewStudentViaForm(page);
    await page.goto(
      `/check-in?token=${PREVIEW_TOKEN_ALIASES.valid}&gpsSim=delay&gpsLat=10.762700&gpsLng=106.660200`,
    );
    const gps = page.getByTestId("gps-capture-step");
    await expect(gps).toBeVisible({ timeout: 20_000 });
    await expect(gps).toContainText("Vị trí đã sẵn sàng", { timeout: 20_000 });
    await expect(gps).toHaveAttribute("aria-busy", "false");
    await expect(page.getByTestId("check-in-submit")).toBeEnabled();
  });

  // TC-AC-06-021 — grouped list discovery with listing toolbar
  test("instructor discovers active session from grouped list and opens QR tab", async ({
    page,
  }) => {
    await page.setViewportSize({ width: 1280, height: 720 });
    await loginPreviewInstructorViaForm(page);
    await page.goto("/sessions");
    await expect(page.getByTestId("sessions-list-page")).toBeVisible();
    await expect(page.getByTestId("sessions-list-toolbar")).toBeVisible();
    await expect(page.getByTestId("sessions-list-search")).toHaveAttribute(
      "placeholder",
      "Tìm theo lớp, môn…",
    );
    await expect(page.getByTestId("sessions-status-chip-all")).toHaveAttribute("aria-pressed", "true");
    await expect(page.getByRole("heading", { name: "Đang diễn ra" })).toBeVisible();
    await page.getByTestId("sessions-status-chip-active").click();
    await expect(page.getByTestId(`session-card-${SESSION_ACTIVE}`)).toBeVisible();
    await page.getByTestId("sessions-list-search").fill("HESD");
    await page.waitForTimeout(350);
    await expect(page.getByTestId(`session-card-${SESSION_ACTIVE}`)).toBeVisible();
    await page.getByTestId(`session-card-${SESSION_ACTIVE}`).click();
    await page.getByRole("tab", { name: "Mã QR" }).click();
    await expect(page.getByTestId("qr-display-panel")).toBeVisible();
    await expect(page.getByTestId("qr-countdown")).toBeVisible();
    const secs = Number(await page.getByTestId("qr-countdown").getAttribute("data-seconds-remaining"));
    expect(secs).toBeGreaterThanOrEqual(1);
    expect(secs).toBeLessThanOrEqual(30);
  });

  // TC-NFR-20-012
  test("QR tab preview meets minimum size before fullscreen launch", async ({ page }) => {
    await page.setViewportSize({ width: 1280, height: 800 });
    await loginPreviewInstructorViaForm(page);
    await page.goto(`/sessions/${SESSION_ACTIVE}?tab=qr`);
    const qrBox = await page.getByTestId("qr-code-image").boundingBox();
    expect(qrBox?.width ?? 0).toBeGreaterThanOrEqual(280);
    await expect(page.getByTestId("qr-present-link")).toBeVisible();
    await page.getByTestId("qr-present-link").click();
    await expect(page).toHaveURL(new RegExp(`/sessions/${SESSION_ACTIVE}/qr-present`));
    await expect(page.getByTestId("qr-code-image")).toBeVisible();
  });

  // TC-AC-06-021 — load-more pagination without duplicate cards
  test("sessions list load-more appends unique session cards", async ({ page }) => {
    await page.setViewportSize({ width: 1280, height: 720 });
    await loginPreviewInstructorViaForm(page);
    await page.goto("/sessions");
    await expect(page.getByTestId("sessions-list-results")).toBeVisible({ timeout: 15_000 });
    await expect(page.locator('[data-testid^="session-card-"]').first()).toBeVisible();
    const before = await page.locator('[data-testid^="session-card-"]').count();
    expect(before).toBeGreaterThan(0);
    await expect(page.getByTestId("sessions-list-load-more")).toBeVisible();
    await page.getByTestId("sessions-list-load-more").click();
    await expect(page.locator('[data-testid^="session-card-"]')).toHaveCount(before * 2, {
      timeout: 10_000,
    });
    const ids = await page
      .locator('[data-testid^="session-card-"]')
      .evaluateAll((els) => els.map((el) => el.getAttribute("data-testid")));
    expect(new Set(ids).size).toBe(ids.length);
  });

  // TC-NFR-20-015
  test("sub-minimum viewport keeps QR at least 280px on qr-present", async ({ page }) => {
    await loginPreviewInstructorViaForm(page);
    await page.setViewportSize({ width: 1024, height: 576 });
    await page.goto(`/sessions/${SESSION_ACTIVE}/qr-present`);
    await expect(page.getByTestId("qr-code-image")).toBeVisible({ timeout: 15_000 });
    const qrBox = await page.getByTestId("qr-code-image").boundingBox();
    expect(qrBox?.width ?? 0).toBeGreaterThanOrEqual(280);
    const fontSize = await page
      .getByTestId("qr-countdown")
      .evaluate((el) => getComputedStyle(el).fontSize);
    expect(parseFloat(fontSize)).toBeGreaterThanOrEqual(48);
  });
});
