import { test, expect } from "@playwright/test";
import {
  loginPreviewAdminViaForm,
  loginPreviewInstructorViaForm,
  refreshPreviewFixtures,
} from "../src/support/auth.js";
import { API_BASE_URL } from "../src/support/constants.js";

const SESSION_ACTIVE = "30000000-0000-4000-8000-000000000301";
const SESSION_CLOSED = "30000000-0000-4000-8000-000000000303";
/** Preview history session closed ~48h ago — instructor edit window expired (BR-10) */
const SESSION_CLOSED_EXPIRED = "31000000-0000-4000-8000-000000000001";

interface RosterRecord {
  id: string;
  status: string;
  institutionalId: string;
}

/**
 * Slice: web-instructor-attendance-roster
 * Source TCs: TC-AC-11-011..012, TC-FR-11-011..012, TC-FR-11-021,
 *   TC-BR-10-011..012, TC-NFR-15-015
 * Generated by browser test agent — do not hand-edit without re-running gate.
 * Last verified: 20260630T204024Z (browser test agent full phase)
 */
test.describe("web-instructor-attendance-roster", () => {
  test.beforeEach(async ({ page }) => {
    await refreshPreviewFixtures(page);
  });

  // TC-FR-11-021 — 14-listing §0 search, filter, sort
  test("roster toolbar search, status filter, and column sort", async ({ page }) => {
    await page.setViewportSize({ width: 1280, height: 720 });
    await loginPreviewInstructorViaForm(page);
    await page.goto("/sessions/sess-3?tab=roster");
    await expect(page.getByTestId("roster-toolbar")).toBeVisible({ timeout: 15_000 });

    await expect(page.locator('[data-testid^="roster-row-"]')).not.toHaveCount(0);
    await expect(page.getByRole("button", { name: /Tải thêm/i })).toHaveCount(0);

    await page.getByTestId("roster-student-search").fill("Nguyễn");
    await expect(page.locator('[data-testid^="roster-row-"]')).toHaveCount(1);
    await page.getByTestId("roster-search-clear").click();

    await page.getByTestId("roster-status-filter").selectOption("Absent");
    const absentRows = page.locator('[data-testid^="roster-row-"]');
    await expect(absentRows).not.toHaveCount(0);
    for (const row of await absentRows.all()) {
      await expect(row).toContainText("Vắng");
    }
    await expect(page.getByTestId("roster-edit-sv2026001")).toBeEnabled();

    await page.getByTestId("roster-sort-status").click();
    await expect(page.getByTestId("roster-sort-status")).toHaveAttribute("aria-sort", "ascending");

    await page.getByTestId("roster-status-filter").selectOption("all");
    await expect(page.locator('[data-testid^="roster-row-"]')).not.toHaveCount(0);
  });

  // TC-AC-11-011 / TC-FR-11-011 / TC-BR-10-011 / TC-NFR-15-015
  test("instructor edits Absent to Present on closed session within edit window", async ({
    page,
  }) => {
    await page.setViewportSize({ width: 1280, height: 720 });
    await loginPreviewInstructorViaForm(page);

    const rosterRes = await page.request.get(
      `${API_BASE_URL}/sessions/${SESSION_CLOSED}/attendance`,
    );
    expect(rosterRes.ok()).toBeTruthy();
    const roster = (await rosterRes.json()) as { records: RosterRecord[] };
    const target = roster.records[0];
    expect(target).toBeTruthy();
    if (target.status !== "Absent") {
      const prep = await page.request.patch(`${API_BASE_URL}/attendance/${target.id}`, {
        data: { status: "Absent", note: "Chuẩn bị kiểm thử chỉnh sửa thủ công" },
      });
      expect(prep.ok()).toBeTruthy();
    }

    await page.goto("/sessions/sess-3?tab=roster");
    await expect(page.getByTestId("attendance-roster-table")).toBeVisible({ timeout: 15_000 });
    await expect(page.getByTestId("roster-edit-window-notice")).toContainText(/giờ/);

    await page.getByTestId("roster-status-filter").selectOption("Absent");
    const rowTestId = `roster-row-${target.institutionalId.toLowerCase()}`;
    const absentRow = page.getByTestId(rowTestId);
    await expect(absentRow).toBeVisible();

    const editButton = page.getByTestId(`roster-edit-${target.institutionalId.toLowerCase()}`);
    await expect(editButton).toBeEnabled();
    await editButton.click();

    await expect(page.getByTestId("attendance-edit-dialog")).toBeVisible();
    await expect(page.getByTestId("edit-window-countdown")).toBeVisible();
    await expect(page.getByText("Trạng thái hiện tại:")).toBeVisible();
    await expect(page.getByTestId("attendance-edit-dialog")).toContainText("Vắng");
    await page.getByTestId("attendance-edit-status").selectOption("Present");
    await page.getByTestId("attendance-edit-note").fill("Xác minh trực tiếp tại lớp");
    await page.getByTestId("attendance-edit-submit").click();

    await expect(page.getByText("Đã cập nhật điểm danh")).toBeVisible({ timeout: 10_000 });
    await page.getByTestId("roster-status-filter").selectOption("all");
    await expect(page.getByTestId(rowTestId)).toContainText("Có mặt");

    const auditToggle = page.getByTestId(rowTestId).getByRole("button", {
      name: /Xem nhật ký chỉnh sửa/i,
    });
    await auditToggle.click();
    const panel = page.getByTestId("attendance-audit-trail-panel");
    await expect(panel).toBeVisible();
    await expect(panel).toContainText("Giảng viên Nguyễn Văn B");
    await expect(panel).toContainText("Vắng");
    await expect(panel).toContainText("Có mặt");
    await expect(panel).toContainText("Xác minh trực tiếp tại lớp");
    await expect(panel.getByRole("button", { name: /xóa|sửa/i })).toHaveCount(0);
  });

  // TC-AC-11-012 / TC-FR-11-012 / TC-BR-10-012 — instructor edit window expired
  test("instructor edit disabled after 24-hour window on closed session", async ({ page }) => {
    await page.setViewportSize({ width: 1280, height: 720 });
    await loginPreviewInstructorViaForm(page);
    await page.goto(`/sessions/${SESSION_CLOSED_EXPIRED}?tab=roster`);
    await expect(page.getByTestId("attendance-roster-table")).toBeVisible({ timeout: 15_000 });

    await expect(page.getByTestId("roster-edit-window-notice")).toContainText(
      /Chỉ phòng đào tạo có thể chỉnh sửa sau thời hạn này/,
    );

    const editButton = page.getByTestId("roster-edit-sv2026001");
    await expect(editButton).toBeDisabled();
    await expect(editButton).toHaveAttribute(
      "title",
      "Chỉ phòng đào tạo có thể chỉnh sửa sau 24 giờ",
    );
  });

  // TC-AC-11-012 contrast — admin retains edit after instructor window expired
  test("admin retains edit on session closed more than 24 hours ago", async ({ page }) => {
    await page.setViewportSize({ width: 1280, height: 720 });
    await loginPreviewAdminViaForm(page);
    await page.goto(`/sessions/${SESSION_CLOSED_EXPIRED}?tab=roster`);
    await expect(page.getByTestId("attendance-roster-table")).toBeVisible({ timeout: 15_000 });
    await expect(page.getByTestId("roster-edit-window-notice")).toHaveCount(0);
    await expect(page.getByTestId("roster-edit-sv2026001")).toBeEnabled();
  });

  test("active session roster allows Pending to Present manual edit", async ({ page }) => {
    await page.setViewportSize({ width: 1280, height: 720 });
    await loginPreviewInstructorViaForm(page);

    const rosterRes = await page.request.get(
      `${API_BASE_URL}/sessions/${SESSION_ACTIVE}/attendance`,
    );
    expect(rosterRes.ok()).toBeTruthy();
    const roster = (await rosterRes.json()) as { records: RosterRecord[] };
    const target = roster.records[0];
    expect(target).toBeTruthy();
    if (target.status !== "Absent" && target.status !== "Pending") {
      const prep = await page.request.patch(`${API_BASE_URL}/attendance/${target.id}`, {
        data: { status: "Absent", note: "Chuẩn bị kiểm thử chỉnh sửa thủ công" },
      });
      expect(prep.ok()).toBeTruthy();
      target.status = "Absent";
    }

    await page.goto("/sessions/sess-1?tab=roster");
    await expect(page.getByTestId("attendance-roster-table")).toBeVisible({ timeout: 15_000 });

    const rowTestId = `roster-row-${target.institutionalId.toLowerCase()}`;
    await page.getByTestId("roster-status-filter").selectOption(target.status);
    await expect(page.getByTestId(rowTestId)).toBeVisible();

    await page.getByTestId(`roster-edit-${target.institutionalId.toLowerCase()}`).click();

    await expect(page.getByTestId("attendance-edit-dialog")).toBeVisible();
    await page.getByTestId("attendance-edit-status").selectOption("Present");
    await page.getByTestId("attendance-edit-submit").click();

    await expect(page.getByText("Đã cập nhật điểm danh")).toBeVisible({ timeout: 10_000 });
    await page.getByTestId("roster-status-filter").selectOption("all");
    await expect(page.getByTestId(rowTestId)).toContainText("Có mặt");
  });

  test("dedicated /sessions/:id/roster route renders roster page", async ({ page }) => {
    await page.setViewportSize({ width: 1280, height: 720 });
    await loginPreviewInstructorViaForm(page);
    await page.goto(`/sessions/${SESSION_CLOSED}/roster`);
    await expect(page.getByTestId("session-roster-page")).toBeVisible({ timeout: 15_000 });
    await expect(page.getByRole("heading", { name: /Danh sách/i })).toBeVisible();
    await expect(page.getByTestId("attendance-roster-table")).toBeVisible();
    await expect(page.getByRole("alert").filter({ hasText: "Buổi học đã kết thúc" })).toBeVisible();
  });

  test("closed session roster shows 24-hour edit window notice", async ({ page }) => {
    await page.setViewportSize({ width: 375, height: 667 });
    await loginPreviewInstructorViaForm(page);
    await page.goto(`/sessions/sess-3?tab=roster`);
    await expect(page.getByTestId("roster-edit-window-notice")).toBeVisible({ timeout: 15_000 });
    await expect(page.getByTestId("roster-toolbar")).toBeVisible();
  });

  test("active session dedicated roster route", async ({ page }) => {
    await page.setViewportSize({ width: 375, height: 667 });
    await loginPreviewInstructorViaForm(page);
    await page.goto(`/sessions/${SESSION_ACTIVE}/roster`);
    await expect(page.getByTestId("session-roster-page")).toBeVisible({ timeout: 15_000 });
    await expect(page.getByTestId("roster-student-search")).toBeVisible();
  });
});
