import { expect, test } from "@playwright/test";
import { API_BASE_URL } from "../src/support/constants.js";
import { STUDENT_PERSONA } from "../src/support/fixtures.js";
import {
  fetchRosterCounts,
  loginItAdmin,
  loginLecturerToRoster,
  openFreshScheduledSession,
  runMobileCheckInJourney,
} from "../src/support/performance-smoke.js";
import { findOpenSessionWithRejectedAttempt } from "../src/support/roster.js";

/**
 * Slice: test-nfr-performance-reliability-smoke
 * Source TCs: TC-AC-20-007, TC-AC-21-009, TC-AC-22-009, TC-NFR-01-008,
 * TC-NFR-03-009, TC-NFR-16-014, TC-NFR-16-015
 * Generated by browser test agent — do not hand-edit without re-running gate.
 */
test.describe("test-nfr-performance-reliability-smoke", () => {
  test("TC-AC-20-007 TC-NFR-01-008: mobile check-in median journey under 30 seconds", async ({
    page,
  }) => {
    const sessionId = await openFreshScheduledSession(page);
    const samples: number[] = [];

    for (const email of [
      STUDENT_PERSONA.email,
      "student2@attendly.local",
      "student3@attendly.local",
    ]) {
      const { elapsedMs, success } = await runMobileCheckInJourney(page, {
        sessionId,
        studentEmail: email,
      });
      expect(success).toBe(true);
      samples.push(elapsedMs);
    }

    samples.sort((a, b) => a - b);
    const median = samples[Math.floor(samples.length / 2)] ?? 0;
    expect(median).toBeLessThan(30_000);
  });

  test("TC-AC-22-009 TC-NFR-03-009: mobile check-in UI success rate at or above 99%", async ({
    page,
  }) => {
    const sessionId = await openFreshScheduledSession(page);
    const outcomes: boolean[] = [];

    for (const email of [
      STUDENT_PERSONA.email,
      "student2@attendly.local",
      "student3@attendly.local",
    ]) {
      const { success } = await runMobileCheckInJourney(page, {
        sessionId,
        studentEmail: email,
      });
      outcomes.push(success);
    }

    const rate = outcomes.filter(Boolean).length / outcomes.length;
    expect(rate).toBeGreaterThanOrEqual(0.99);
  });

  test("TC-AC-21-009: lecturer live roster shows majority checked in without refresh", async ({
    page,
  }) => {
    const sessionId = await openFreshScheduledSession(page);

    for (const email of [
      STUDENT_PERSONA.email,
      "student2@attendly.local",
      "student3@attendly.local",
    ]) {
      const { success } = await runMobileCheckInJourney(page, {
        sessionId,
        studentEmail: email,
      });
      expect(success).toBe(true);
    }

    await loginLecturerToRoster(page, sessionId);
    await expect(page.getByText("Cập nhật theo thời gian thực")).toBeVisible();

    const presentChip = page
      .locator('[aria-label="Tóm tắt điểm danh"]')
      .getByText("Có mặt")
      .locator("..")
      .locator("span")
      .last();
    const lateChip = page
      .locator('[aria-label="Tóm tắt điểm danh"]')
      .getByText("Muộn")
      .locator("..")
      .locator("span")
      .last();
    const pendingChip = page
      .locator('[aria-label="Tóm tắt điểm danh"]')
      .getByText("Chưa điểm danh")
      .locator("..")
      .locator("span")
      .last();

    const present = Number((await presentChip.textContent()) ?? "0");
    const late = Number((await lateChip.textContent()) ?? "0");
    const pending = Number((await pendingChip.textContent()) ?? "0");
    const checkedIn = present + late;
    const total = checkedIn + pending;

    expect(checkedIn / total).toBeGreaterThan(0.5);
  });

  test("TC-NFR-16-014: live roster exposes rejectedAttempts and failure outcome badges", async ({
    page,
  }) => {
    const fixture = await findOpenSessionWithRejectedAttempt(page);
    test.skip(!fixture, "No open session with rejected attempts in preview stack");

    const apiCounts = await fetchRosterCounts(page, fixture!.sessionId);
    await loginLecturerToRoster(page, fixture!.sessionId);

    const rejectedChip = page
      .locator('[aria-label="Tóm tắt điểm danh"]')
      .getByText("Lần thử lỗi")
      .locator("..")
      .locator("span")
      .last();
    await expect(rejectedChip).toHaveText(String(apiCounts.rejectedAttempts));

    const failureRow = page.locator("tr", { hasText: fixture!.row.studentCode });
    await expect(failureRow.locator("[title]").first()).toBeVisible();
    await expect(page.getByText("Lần thử lỗi")).toBeVisible();
  });

  test("TC-NFR-16-015: ITAdmin reviews audit logs with technical filters and read-only boundary", async ({
    page,
  }) => {
    await loginItAdmin(page, "/audit/logs");

    await expect(page.getByRole("heading", { name: "Nhật ký audit" })).toBeVisible();
    await expect(page.getByTestId("audit-log-list")).toBeVisible();
    await expect(page.getByText(/Không thể tải nhật ký audit/i)).toHaveCount(0);

    await page.getByLabel("Lọc theo loại hành động").selectOption("SessionOpen");
    await expect(page).toHaveURL(/actionType=SessionOpen/);

    await page.getByLabel("Từ ngày").fill("2026-07-01");
    await page.getByLabel("Đến ngày").fill("2026-07-03");
    await expect(page).toHaveURL(/from=2026-07-01/);
    await expect(page).toHaveURL(/to=2026-07-03/);

    await expect(page.getByRole("button", { name: /Sửa|Xóa/i })).toHaveCount(0);
    await expect(page.getByText("Chế độ chỉ đọc")).toHaveCount(0);

    const health = await page.request.get(`${API_BASE_URL}/health`);
    expect(health.ok()).toBe(true);
    const body = (await health.json()) as { status?: string; db?: string };
    expect(body.status).toBe("ok");
    expect(body.db).toBe("connected");
  });
});
