import { expect, test } from "@playwright/test";
import { loginViaApi } from "../src/support/auth.js";
import { API_BASE_URL, WEB_BASE_URL } from "../src/support/constants.js";
import {
  ACADEMIC_ADMIN_SEED_EMAIL,
  LECTURER_PERSONA,
  SEED_FIXTURE_IDS,
  STUDENT_PERSONA,
} from "../src/support/fixtures.js";
import {
  findClosedSessionWithAbsent,
  loginLecturerToRoster,
} from "../src/support/roster.js";

const SEED_TERM_ID = "20000000-0000-4000-8000-000000000001";
const OUT_OF_SCOPE_SECTION_ID = "00000000-0000-4000-8000-000000000099";
const UNASSIGNED_SECTION_ID = "50000000-0000-4000-8000-000000000002";

/**
 * Slice: test-e2e-role-scope-and-export
 * Source TCs: TC-AC-15-009, TC-AC-16-012, TC-AC-16-013, TC-AC-17-009,
 * TC-AC-23-015, TC-AC-23-016, TC-NFR-09-014, TC-NFR-09-015,
 * TC-NFR-10-014, TC-NFR-10-015
 * Generated by browser test agent — do not hand-edit without re-running gate.
 */
test.describe("test-e2e-role-scope-and-export", () => {
  test.beforeEach(async ({ page }) => {
    await page.setViewportSize(LECTURER_PERSONA.viewport);
  });

  test("TC-AC-15-009: lecturer exports attendance scoped to assigned section only", async ({
    page,
  }) => {
    await loginViaApi(page, LECTURER_PERSONA.email, LECTURER_PERSONA.password, "/reports/attendance");

    await expect(page.getByRole("heading", { name: "Báo cáo điểm danh" })).toBeVisible();

    const sectionOptions = await page
      .getByLabel("Lọc theo lớp học phần")
      .locator("option")
      .allTextContents();
    expect(sectionOptions).toContain("SE101-01");
    expect(sectionOptions.some((label) => label.includes("SE101-02"))).toBe(false);

    await page
      .getByLabel("Lọc theo lớp học phần")
      .selectOption(SEED_FIXTURE_IDS.section);
    await expect(page).toHaveURL(/classSectionId=/);

    await page.getByRole("button", { name: "Xuất CSV" }).click();
    await expect(page.getByRole("heading", { name: "Xác nhận phạm vi xuất CSV" })).toBeVisible();
    await expect(page.getByText("Giảng viên · chỉ các lớp được phân công")).toBeVisible();
    await expect(page.locator("dt:has-text('Lớp học phần') + dd")).toHaveText("SE101-01");

    const downloadPromise = page.waitForEvent("download");
    await page.getByRole("button", { name: "Xác nhận xuất CSV" }).click();
    await expect(page.getByText("Xuất CSV thành công")).toBeVisible({ timeout: 15_000 });
    const download = await downloadPromise;
    expect(await download.path()).toBeTruthy();
  });

  test("TC-AC-16-012: student blocked from institution report and export surfaces", async ({
    page,
  }) => {
    await page.setViewportSize(STUDENT_PERSONA.viewport);
    await loginViaApi(page, STUDENT_PERSONA.email, STUDENT_PERSONA.password, "/reports/attendance");

    await expect(page.getByText("Không có quyền truy cập")).toBeVisible();
    await expect(page.getByRole("table")).toHaveCount(0);
    await expect(page.getByRole("button", { name: "Xuất CSV" })).toHaveCount(0);
    await expect(
      page.getByRole("link", { name: "lịch sử điểm danh cá nhân" }),
    ).toBeVisible();

    const nav = page.locator("nav");
    await expect(nav.getByRole("link", { name: /báo cáo/i })).toHaveCount(0);
    await expect(nav.getByRole("link", { name: /buổi học/i })).toHaveCount(0);
    await expect(nav.getByRole("link", { name: /audit/i })).toHaveCount(0);

    const loginRes = await page.request.post(`${API_BASE_URL}/auth/login`, {
      data: { email: STUDENT_PERSONA.email, password: STUDENT_PERSONA.password },
    });
    const token = (await loginRes.json()).data?.accessToken as string;
    const exportRes = await page.request.post(`${API_BASE_URL}/exports/attendance`, {
      headers: {
        Authorization: `Bearer ${token}`,
        "Idempotency-Key": `pw-role-scope-student-${Date.now()}`,
        "Content-Type": "application/json",
      },
      data: { format: "csv", filters: { termId: SEED_TERM_ID } },
    });
    expect(exportRes.status()).toBe(403);
  });

  test("TC-AC-16-013: lecturer sees denial for tampered out-of-scope classSectionId", async ({
    page,
  }) => {
    await loginViaApi(page, LECTURER_PERSONA.email, LECTURER_PERSONA.password, "/reports/attendance");

    const sectionOptions = await page
      .getByLabel("Lọc theo lớp học phần")
      .locator("option")
      .allTextContents();
    expect(sectionOptions).toContain("SE101-01");
    expect(sectionOptions.some((label) => label.includes("SE101-02"))).toBe(false);

    await page.goto(
      `${WEB_BASE_URL}/reports/attendance?classSectionId=${OUT_OF_SCOPE_SECTION_ID}&termId=${SEED_TERM_ID}`,
    );
    await expect(page.getByText("Ngoài phạm vi được phép")).toBeVisible();
    await expect(page.getByRole("table")).toHaveCount(0);

    const loginRes = await page.request.post(`${API_BASE_URL}/auth/login`, {
      data: { email: LECTURER_PERSONA.email, password: LECTURER_PERSONA.password },
    });
    const token = (await loginRes.json()).data?.accessToken as string;
    const exportRes = await page.request.post(`${API_BASE_URL}/exports/attendance`, {
      headers: {
        Authorization: `Bearer ${token}`,
        "Idempotency-Key": `pw-role-scope-oos-${Date.now()}`,
        "Content-Type": "application/json",
      },
      data: {
        format: "csv",
        filters: { termId: SEED_TERM_ID, classSectionId: OUT_OF_SCOPE_SECTION_ID },
      },
    });
    expect(exportRes.status()).toBe(403);
    const body = await exportRes.json();
    expect(body.error?.code).toMatch(/OutOfScope|Forbidden/);
  });

  test("TC-AC-17-009: export completion creates queryable audit trail", async ({ page }) => {
    await loginViaApi(page, LECTURER_PERSONA.email, LECTURER_PERSONA.password, "/reports/attendance");

    await page
      .getByLabel("Lọc theo lớp học phần")
      .selectOption(SEED_FIXTURE_IDS.section);
    await page.getByRole("button", { name: "Xuất CSV" }).click();
    await page.getByRole("button", { name: "Xác nhận xuất CSV" }).click();
    await expect(page.getByText("Xuất CSV thành công")).toBeVisible({ timeout: 15_000 });

    const adminLogin = await page.request.post(`${API_BASE_URL}/auth/login`, {
      data: { email: ACADEMIC_ADMIN_SEED_EMAIL, password: LECTURER_PERSONA.password },
    });
    const adminToken = (await adminLogin.json()).data?.accessToken as string;
    const auditRes = await page.request.get(
      `${API_BASE_URL}/audit-logs?actionType=Export&page=1&pageSize=10`,
      { headers: { Authorization: `Bearer ${adminToken}` } },
    );
    expect(auditRes.ok()).toBe(true);
    const auditBody = await auditRes.json();
    const exportEntry = auditBody.data?.find(
      (row: { actorUserId: string; format: string }) =>
        row.actorUserId === SEED_FIXTURE_IDS.lecturerUser && row.format === "csv",
    );
    expect(exportEntry).toBeTruthy();
    expect(exportEntry.scopeFilterSummary).toContain(SEED_FIXTURE_IDS.section);

    await loginViaApi(
      page,
      ACADEMIC_ADMIN_SEED_EMAIL,
      LECTURER_PERSONA.password,
      "/audit/logs?actionType=Export&from=2026-07-01&to=2026-07-03",
    );
    await expect(page.getByText("Nguyễn Văn Giảng").first()).toBeVisible();
    await expect(page.getByText(/csv · termId=/).first()).toBeVisible();
  });

  test("TC-AC-23-015: student blocked from session control, report, and export surfaces", async ({
    page,
  }) => {
    await page.setViewportSize(STUDENT_PERSONA.viewport);
    await loginViaApi(page, STUDENT_PERSONA.email, STUDENT_PERSONA.password, "/check-in");

    const nav = page.locator("nav");
    await expect(nav.getByRole("link", { name: /buổi học/i })).toHaveCount(0);
    await expect(nav.getByRole("link", { name: /báo cáo/i })).toHaveCount(0);
    await expect(nav.getByRole("link", { name: /audit/i })).toHaveCount(0);

    await page.goto(`${WEB_BASE_URL}/lecturer/sessions`);
    await expect(page.getByText(/Không có quyền|Không thể tải/i)).toBeVisible();
    await expect(page.getByRole("link", { name: "Mở điểm danh" })).toHaveCount(0);

    await page.goto(`${WEB_BASE_URL}/reports/attendance`);
    await expect(page.getByText("Không có quyền truy cập")).toBeVisible();
    await expect(page.getByRole("table")).toHaveCount(0);
    await expect(page.getByRole("button", { name: "Xuất CSV" })).toHaveCount(0);
  });

  test("TC-AC-23-016: lecturer scoped session control and export; denies foreign section tamper", async ({
    page,
  }) => {
    await loginViaApi(page, LECTURER_PERSONA.email, LECTURER_PERSONA.password, "/lecturer/sessions");

    await expect(page.getByText("SE101-01").first()).toBeVisible();
    await expect(page.getByText("SE101-02")).toHaveCount(0);

    const sectionOptions = await page
      .getByLabel("Lọc theo lớp học phần")
      .locator("option")
      .allTextContents();
    expect(sectionOptions).toContain("SE101-01");
    expect(sectionOptions.some((label) => label.includes("SE101-02"))).toBe(false);

    const openFromList = page.getByRole("link", { name: "Mở điểm danh" }).first();
    if ((await openFromList.count()) > 0) {
      await openFromList.click();
    } else {
      const openRow = page.locator("tbody tr").filter({ hasText: "Đang mở" }).first();
      await openRow.getByRole("link", { name: "Chi tiết" }).click();
    }
    await expect(page).toHaveURL(/\/lecturer\/sessions\/[0-9a-f-]+$/);
    await expect(page.getByText("Đang mở").first()).toBeVisible();

    await page.goto(`${WEB_BASE_URL}/reports/attendance`);
    const reportSections = await page
      .getByLabel("Lọc theo lớp học phần")
      .locator("option")
      .allTextContents();
    expect(reportSections).toContain("SE101-01");

    await page.goto(
      `${WEB_BASE_URL}/reports/attendance?classSectionId=${UNASSIGNED_SECTION_ID}&termId=${SEED_TERM_ID}`,
    );
    await expect(page.getByText("Ngoài phạm vi được phép")).toBeVisible();
    await expect(page.getByRole("table")).toHaveCount(0);
  });

  test("TC-NFR-09-014: student blocked from audit log listing and detail surfaces", async ({
    page,
  }) => {
    await page.setViewportSize(STUDENT_PERSONA.viewport);
    await loginViaApi(page, STUDENT_PERSONA.email, STUDENT_PERSONA.password, "/me/attendance");

    await expect(page.locator("nav").getByRole("link", { name: /audit/i })).toHaveCount(0);

    await page.goto(`${WEB_BASE_URL}/audit/logs`);
    await expect(page.getByText(/Không có quyền truy cập/i)).toBeVisible();
    await expect(page.getByTestId("audit-log-list")).toHaveCount(0);
    await expect(page.locator("article")).toHaveCount(0);

    const loginRes = await page.request.post(`${API_BASE_URL}/auth/login`, {
      data: { email: STUDENT_PERSONA.email, password: STUDENT_PERSONA.password },
    });
    const token = (await loginRes.json()).data?.accessToken as string;
    const auditRes = await page.request.get(`${API_BASE_URL}/audit-logs?page=1&pageSize=5`, {
      headers: { Authorization: `Bearer ${token}` },
    });
    expect(auditRes.status()).toBe(403);
  });

  test("TC-NFR-09-015: lecturer export section filter scoped; foreign-section tamper denied", async ({
    page,
  }) => {
    await loginViaApi(page, LECTURER_PERSONA.email, LECTURER_PERSONA.password, "/reports/attendance");

    const sectionOptions = await page
      .getByLabel("Lọc theo lớp học phần")
      .locator("option")
      .allTextContents();
    expect(sectionOptions).toEqual(["Tất cả lớp", "SE101-01"]);

    await page
      .getByLabel("Lọc theo lớp học phần")
      .selectOption(SEED_FIXTURE_IDS.section);
    await page.getByRole("button", { name: "Xuất CSV" }).click();
    await page.getByRole("button", { name: "Xác nhận xuất CSV" }).click();
    await expect(page.getByText("Xuất CSV thành công")).toBeVisible({ timeout: 15_000 });

    await page.goto(
      `${WEB_BASE_URL}/reports/attendance?classSectionId=${UNASSIGNED_SECTION_ID}&termId=${SEED_TERM_ID}`,
    );
    await expect(page.getByText("Ngoài phạm vi được phép")).toBeVisible();
    await expect(page.getByRole("table")).toHaveCount(0);

    const loginRes = await page.request.post(`${API_BASE_URL}/auth/login`, {
      data: { email: LECTURER_PERSONA.email, password: LECTURER_PERSONA.password },
    });
    const token = (await loginRes.json()).data?.accessToken as string;
    const exportRes = await page.request.post(`${API_BASE_URL}/exports/attendance`, {
      headers: {
        Authorization: `Bearer ${token}`,
        "Idempotency-Key": `pw-nfr09-oos-${Date.now()}`,
        "Content-Type": "application/json",
      },
      data: {
        format: "csv",
        filters: { termId: SEED_TERM_ID, classSectionId: UNASSIGNED_SECTION_ID },
      },
    });
    expect(exportRes.status()).toBe(403);
  });

  test("TC-NFR-10-014: manual correction gates reason and writes auditable mutation", async ({
    page,
  }) => {
    const fixture = await findClosedSessionWithAbsent(page);
    test.skip(!fixture, "No closed session with absent students in preview stack");

    await loginLecturerToRoster(page, fixture!.sessionId);
    const row = page.locator("tr", { hasText: fixture!.row.studentCode });
    await row.getByRole("button", { name: "Điều chỉnh" }).click();
    await expect(page.getByTestId("manual-correction-dialog")).toBeVisible();

    const save = page.getByRole("button", { name: "Lưu điều chỉnh" });
    await expect(save).toBeDisabled();

    await page.getByLabel("Lý do").fill("ngắn");
    await expect(save).toBeDisabled();

    await page
      .getByLabel("Lý do")
      .fill("Sinh viên có mặt nhưng thiết bị lỗi GPS khi điểm danh.");
    await expect(save).toBeEnabled();
    await save.click();

    await expect(page.getByTestId("manual-correction-dialog")).toHaveCount(0);
    await expect(row.getByText("Có mặt (thủ công)")).toBeVisible();

    const adminLogin = await page.request.post(`${API_BASE_URL}/auth/login`, {
      data: { email: ACADEMIC_ADMIN_SEED_EMAIL, password: LECTURER_PERSONA.password },
    });
    const adminToken = (await adminLogin.json()).data?.accessToken as string;
    const auditRes = await page.request.get(
      `${API_BASE_URL}/audit-logs?actionType=manual_update&page=1&pageSize=5`,
      { headers: { Authorization: `Bearer ${adminToken}` } },
    );
    expect(auditRes.ok()).toBe(true);
    const auditBody = await auditRes.json();
    const entry = auditBody.data?.find(
      (row: { actorUserId: string; newStatus: string }) =>
        row.actorUserId === SEED_FIXTURE_IDS.lecturerUser && row.newStatus === "Manual Present",
    );
    expect(entry).toBeTruthy();
    expect(entry.oldStatus).toBe("Absent");
    expect(entry.reason).toContain("GPS");
  });

  test("TC-NFR-10-015: student cannot access manual correction or roster edit controls", async ({
    page,
  }) => {
    await page.setViewportSize(STUDENT_PERSONA.viewport);
    await loginViaApi(page, STUDENT_PERSONA.email, STUDENT_PERSONA.password, "/me/attendance");

    await expect(page.getByRole("heading", { name: "Lịch sử điểm danh" })).toBeVisible();
    await expect(page.getByRole("button", { name: /Điều chỉnh|Chỉnh sửa|Sửa/i })).toHaveCount(0);
    await expect(page.getByRole("button", { name: "Xuất CSV" })).toHaveCount(0);

    await page.goto(
      `${WEB_BASE_URL}/lecturer/sessions/${SEED_FIXTURE_IDS.scheduledSession}/roster`,
    );
    await expect(page.getByText(/Không có quyền|Không thể tải/i)).toBeVisible();
    await expect(page.getByRole("button", { name: /Điều chỉnh|Chỉnh sửa/i })).toHaveCount(0);
  });
});
