import { expect, test } from "@playwright/test";
import { loginViaApi } from "../src/support/auth.js";
import { WEB_BASE_URL } from "../src/support/constants.js";
import {
  STALE_QR_TOKEN,
  ensureStudentCheckedIn,
  fetchCurrentQr,
  fetchRoster,
  findOpenSessionWithPending,
  findOpenSessionWithPresentAndPending,
  loginToken,
  prepareStudentMobile,
  seedAuth,
} from "../src/support/critical-path.js";
import { LECTURER_PERSONA, SEED_FIXTURE_IDS, STUDENT_PERSONA } from "../src/support/fixtures.js";

/**
 * Slice: test-backend-integration-critical-path
 * Source TCs: TC-AC-01-008, TC-AC-04-008, TC-AC-08-009, TC-AC-12-010,
 * TC-AC-18-010, TC-NFR-07-009.
 * Generated by browser test agent — do not hand-edit without re-running gate.
 */
test.describe("test-backend-integration-critical-path", () => {
  test("TC-AC-01-008: lecturer opens scheduled session and sees QR state", async ({
    page,
  }) => {
    await page.setViewportSize(LECTURER_PERSONA.viewport);
    await loginViaApi(
      page,
      LECTURER_PERSONA.email,
      LECTURER_PERSONA.password,
      "/lecturer/sessions",
    );

    await page.getByRole("link", { name: "Mở điểm danh" }).first().click();
    await expect(page).toHaveURL(/\/lecturer\/sessions\/[0-9a-f-]+$/);
    await expect(page.getByText("Đang mở").first()).toBeVisible();
    await expect(page.getByTestId("qr-display-canvas")).toBeVisible();
    await expect(page.getByText(/Còn \d+ giây/)).toBeVisible();
    await expect(page.getByText(/Lúc mở/)).toBeVisible();
  });

  test("TC-AC-04-008: expired QR shows Vietnamese retry path", async ({ page }) => {
    const lecturerToken = await loginToken(page, LECTURER_PERSONA.email);
    const studentToken = await loginToken(page, STUDENT_PERSONA.email);
    await prepareStudentMobile(page, studentToken);

    await page.goto(`${WEB_BASE_URL}/check-in?token=${STALE_QR_TOKEN}`);
    await page.getByRole("button", { name: "Cho phép vị trí" }).click();
    await expect(page.getByText("Mã QR đã hết hạn")).toBeVisible();
    await expect(page.getByRole("button", { name: "Thử lại" })).toBeVisible();

    await page.getByRole("button", { name: "Thử lại" }).click();
    const freshQr = await fetchCurrentQr(
      page,
      lecturerToken,
      SEED_FIXTURE_IDS.scheduledSession,
    );
    await page.goto(`${WEB_BASE_URL}/check-in?token=${freshQr}`);
    await expect(
      page.getByRole("button", { name: "Xác nhận điểm danh" }),
    ).toBeVisible();
  });

  test("TC-AC-08-009 TC-NFR-07-009: duplicate check-in info alert without retry", async ({
    page,
  }) => {
    const lecturerToken = await loginToken(page, LECTURER_PERSONA.email);
    const studentToken = await loginToken(page, STUDENT_PERSONA.email);
    const openSession =
      (await listOpenSession(page, lecturerToken))?.classSessionId ??
      SEED_FIXTURE_IDS.openSession;

    await ensureStudentCheckedIn(page, {
      lecturerToken,
      studentToken,
      sessionId: openSession,
    });

    const dupQr = await fetchCurrentQr(page, lecturerToken, openSession);
    await prepareStudentMobile(page, studentToken);
    await page.goto(`${WEB_BASE_URL}/check-in?token=${dupQr}`);
    await page.getByRole("button", { name: "Cho phép vị trí" }).click();

    await expect(
      page.getByText("Bạn đã điểm danh buổi học này rồi."),
    ).toBeVisible();
    await expect(page.getByRole("button", { name: "Thử lại" })).toHaveCount(0);
    await expect(page.getByText(/Có mặt|Đi trễ/)).toBeVisible();
    await expect(page.getByText(/Lúc|\d{2}:\d{2}/)).toBeVisible();

    await page.reload();
    if (await page.getByRole("button", { name: "Cho phép vị trí" }).isVisible()) {
      await page.getByRole("button", { name: "Cho phép vị trí" }).click();
    }
    await expect(
      page.getByText("Bạn đã điểm danh buổi học này rồi."),
    ).toBeVisible();
  });

  test("TC-AC-12-010: close session finalizes pending students as Absent", async ({
    page,
  }) => {
    const lecturerToken = await loginToken(page, LECTURER_PERSONA.email);
    const fixture = await findOpenSessionWithPresentAndPending(page, lecturerToken);
    test.skip(!fixture, "No open session with mixed present/pending in preview stack");

    await page.setViewportSize(LECTURER_PERSONA.viewport);
    await seedAuth(page, lecturerToken);
    await page.goto(`${WEB_BASE_URL}/lecturer/sessions/${fixture!.sessionId}`);

    await expect(page.getByText("Đang mở").first()).toBeVisible();
    await expect(page.getByTestId("qr-display-canvas")).toBeVisible();
    await page.getByRole("button", { name: "Đóng điểm danh" }).click();
    await page
      .locator('[data-testid="confirm-action-modal"], [role="dialog"]')
      .getByRole("button", { name: /Xác nhận/ })
      .last()
      .click()
      .catch(async () => {
        await page.getByRole("button", { name: /Xác nhận đóng/ }).click();
      });

    await expect(page.getByText("Đã đóng").first()).toBeVisible();
    await expect(page.getByTestId("qr-display-canvas")).toHaveCount(0);

    await page.goto(`${WEB_BASE_URL}/lecturer/sessions/${fixture!.sessionId}/roster`);
    await expect(page.getByText("Vắng").first()).toBeVisible();
    await expect(page.getByText("Cập nhật theo thời gian thực")).toHaveCount(0);

    const roster = await fetchRoster(page, lecturerToken, fixture!.sessionId);
    expect(roster?.counts.absent ?? 0).toBeGreaterThan(0);
    expect(roster?.counts.pending ?? 0).toBe(0);
  });

  test("TC-AC-18-010: expired QR maps to roster rejected attempt badge", async ({
    page,
  }) => {
    const lecturerToken = await loginToken(page, LECTURER_PERSONA.email);
    const studentToken = await loginToken(page, STUDENT_PERSONA.email);
    const pendingSession = await findOpenSessionWithPending(page, lecturerToken);
    test.skip(!pendingSession, "No open session with pending students in preview stack");

    const qrPayload = await fetchCurrentQr(
      page,
      lecturerToken,
      pendingSession!.sessionId,
    );
    const before = await fetchRoster(page, lecturerToken, pendingSession!.sessionId);
    const rejectedBefore = before?.counts.rejectedAttempts ?? 0;

    await page.waitForTimeout(35_000);

    await prepareStudentMobile(page, studentToken);
    await page.goto(`${WEB_BASE_URL}/check-in?token=${qrPayload}`);
    await page.getByRole("button", { name: "Cho phép vị trí" }).click();
    await expect(page.getByText("Mã QR đã hết hạn")).toBeVisible();

    await page.goto(`${WEB_BASE_URL}/check-in?token=${qrPayload}`);
    await page.getByRole("button", { name: "Cho phép vị trí" }).click().catch(() => {});
    await expect(page.getByText("Mã QR đã hết hạn")).toBeVisible();

    const after = await fetchRoster(page, lecturerToken, pendingSession!.sessionId);
    expect(after?.counts.rejectedAttempts ?? 0).toBeGreaterThan(rejectedBefore);

    await page.setViewportSize(LECTURER_PERSONA.viewport);
    await seedAuth(page, lecturerToken);
    await page.goto(
      `${WEB_BASE_URL}/lecturer/sessions/${pendingSession!.sessionId}/roster`,
    );
    await expect(page.getByText(/QR hết hạn|ExpiredQr/)).toBeVisible();
  });
});

async function listOpenSession(
  page: import("@playwright/test").Page,
  lecturerToken: string,
): Promise<{ classSessionId: string } | undefined> {
  const response = await page.request.get(
    `${process.env.PLAYWRIGHT_API_BASE_URL ?? "http://localhost:3001/api/v1"}/class-sessions?page=1&pageSize=50`,
    { headers: { Authorization: `Bearer ${lecturerToken}` } },
  );
  const body = (await response.json()) as {
    data?: Array<{ classSessionId: string; state: string }>;
  };
  return body.data?.find((session) => session.state === "Open");
}
