import { expect, test } from "@playwright/test";
import { loginViaApi } from "../src/support/auth.js";
import { WEB_BASE_URL } from "../src/support/constants.js";
import {
  LECTURER_PERSONA,
  SEED_FIXTURE_IDS,
  STUDENT_PERSONA,
} from "../src/support/fixtures.js";

const SEED_TERM_ID = "20000000-0000-4000-8000-000000000001";
const OUT_OF_SCOPE_SECTION_ID = "50000000-0000-4000-8000-000000000002";

/**
 * Slice: web-student-attendance-history
 * Source TCs: TC-FR-37-014, TC-FR-37-015, TC-BR-19-018, TC-BR-19-019,
 * TC-AC-16-012, TC-AC-16-013
 * Generated by browser test agent — do not hand-edit without re-running gate.
 */
test.describe("web-student-attendance-history", () => {
  test("TC-FR-37-014: student PG-03 history lists filters badges pagination without export", async ({
    page,
  }) => {
    await page.setViewportSize(STUDENT_PERSONA.viewport);
    await loginViaApi(page, STUDENT_PERSONA.email, STUDENT_PERSONA.password, "/me/attendance");

    await expect(page.getByRole("heading", { name: "Lịch sử điểm danh" })).toBeVisible();
    await expect(page.getByTestId("attendance-history-list")).toBeVisible();
    await expect(page.getByRole("heading", { name: "SE101-01" })).toBeVisible();
    await expect(page.getByText("Có mặt").first()).toBeVisible();
    await expect(page.getByText("Đi trễ").first()).toBeVisible();
    await expect(page.getByText("QR").first()).toBeVisible();
    await expect(page.getByRole("button", { name: "Xuất CSV" })).toHaveCount(0);

    await page.getByLabel("Lọc theo lớp học phần").selectOption(SEED_FIXTURE_IDS.section);
    await expect(page).toHaveURL(/classSectionId=/);

    await page.goto(
      `${WEB_BASE_URL}/me/attendance?termId=${SEED_TERM_ID}&classSectionId=${SEED_FIXTURE_IDS.section}&sortBy=date&sortOrder=desc&page=1&pageSize=1`,
    );
    await expect(page.getByText("Trang 1 / 2")).toBeVisible();
    await page.getByRole("button", { name: "Trang sau" }).click();
    await expect(page).toHaveURL(/page=2/);
    await expect(page).toHaveURL(/pageSize=1/);
    await expect(page).toHaveURL(/sortBy=date/);
    await expect(page).toHaveURL(/sortOrder=desc/);
  });

  test("TC-FR-37-015 TC-AC-16-012: student denied institution report without data leakage", async ({
    page,
  }) => {
    await page.setViewportSize(STUDENT_PERSONA.viewport);
    await loginViaApi(page, STUDENT_PERSONA.email, STUDENT_PERSONA.password, "/reports/attendance");

    await expect(page.getByText("Không có quyền truy cập")).toBeVisible();
    await expect(page.getByRole("table")).toHaveCount(0);
    await expect(
      page.getByRole("link", { name: "lịch sử điểm danh cá nhân" }),
    ).toBeVisible();

    await page.goto(`${WEB_BASE_URL}/me/attendance`);
    await expect(page.getByTestId("attendance-history-list")).toBeVisible();
    await expect(page.getByText("SV002")).toHaveCount(0);
    await expect(page.getByText("SV003")).toHaveCount(0);
  });

  test("TC-BR-19-018: student cannot reach report or export surfaces from browser", async ({
    page,
  }) => {
    await loginViaApi(page, STUDENT_PERSONA.email, STUDENT_PERSONA.password, "/");

    await page.goto(`${WEB_BASE_URL}/reports/attendance`);
    await expect(page.getByText("Không có quyền truy cập")).toBeVisible();
    await expect(page.getByRole("button", { name: "Xuất CSV" })).toHaveCount(0);

    await page.goto(`${WEB_BASE_URL}/exports/attendance`);
    await expect(page.getByRole("table")).toHaveCount(0);
    await expect(page.getByText("Không có quyền truy cập")).toHaveCount(0);

    const nav = page.locator("nav");
    await expect(nav.getByRole("link", { name: /báo cáo/i })).toHaveCount(0);
    await expect(nav.getByRole("link", { name: /xuất/i })).toHaveCount(0);
  });

  test("TC-BR-19-019: lecturer sees out-of-scope denial for tampered section filter", async ({
    page,
  }) => {
    await page.setViewportSize(LECTURER_PERSONA.viewport);
    await loginViaApi(
      page,
      LECTURER_PERSONA.email,
      LECTURER_PERSONA.password,
      "/reports/attendance",
    );

    const sectionOptions = await page
      .getByLabel("Lọc theo lớp học phần")
      .locator("option")
      .allTextContents();
    expect(sectionOptions).toEqual(["Tất cả lớp", "SE101-01"]);

    await page.goto(
      `${WEB_BASE_URL}/reports/attendance?classSectionId=${OUT_OF_SCOPE_SECTION_ID}`,
    );
    await expect(page.getByText("Ngoài phạm vi được phép")).toBeVisible();
    await expect(page.getByRole("table")).toHaveCount(0);
    await expect(page.getByText("SV002")).toHaveCount(0);
  });

  test("TC-AC-16-013: lecturer export denied for out-of-scope classSectionId", async ({
    page,
  }) => {
    await page.setViewportSize(LECTURER_PERSONA.viewport);
    await loginViaApi(
      page,
      LECTURER_PERSONA.email,
      LECTURER_PERSONA.password,
      `/reports/attendance?classSectionId=${OUT_OF_SCOPE_SECTION_ID}`,
    );

    await expect(page.getByText("Ngoài phạm vi được phép")).toBeVisible();
    await page.getByRole("button", { name: "Xuất CSV" }).click();
    await expect(page.getByText("Không thể xuất")).toBeVisible();
    await expect(page.getByText(/Xuất CSV bị từ chối/)).toBeVisible();
  });
});
