import { expect, test } from "@playwright/test";
import { WEB_BASE_URL } from "../src/support/constants.js";
import { loginViaApi } from "../src/support/auth.js";
import { LECTURER_PERSONA, STUDENT_PERSONA } from "../src/support/fixtures.js";
import { loginLecturerToRoster } from "../src/support/roster.js";
import {
  fetchSessionQr,
  findOpenSessionWithLateRows,
  findOpenSessionWithPresentAndLate,
  loginAcademicAdminPolicies,
} from "../src/support/policy-admin.js";

/**
 * Slice: web-academic-admin-policy-management
 * Source TCs: TC-FR-24-014, TC-FR-24-015, TC-FR-25-015, TC-FR-25-016,
 * TC-BR-20-015, TC-BR-20-016, TC-AC-09-009, TC-AC-09-010, TC-AC-10-009, TC-AC-10-010
 * Acceptance tags: FR-24, FR-25, BR-20, AC-09, AC-10
 * Generated by browser test agent — do not hand-edit without re-running gate.
 */
test.describe("web-academic-admin-policy-management", () => {
  test("TC-FR-24-014: PG-12 policies list scope filter, pagination, and sort", async ({
    page,
  }) => {
    await page.setViewportSize({ width: 1280, height: 720 });
    await loginAcademicAdminPolicies(page);

    await expect(page.getByRole("heading", { name: "Danh sách chính sách" })).toBeVisible();
    await expect(page.getByTestId("policy-list")).toBeVisible();
    await expect(page.getByTestId("table-toolbar")).toBeVisible();
    await expect(page.getByRole("table", { name: "Danh sách chính sách điểm danh" })).toBeVisible();
    await expect(page.getByRole("columnheader", { name: "Cấp phạm vi" })).toBeVisible();
    await expect(page.getByRole("columnheader", { name: "Tên phạm vi" })).toBeVisible();
    await expect(page.getByRole("columnheader", { name: "Cập nhật" })).toBeVisible();

    await page.getByLabel("Lọc theo trạng thái điểm danh").selectOption("ClassSection");
    await expect(page).toHaveURL(/scopeLevel=ClassSection/);
    await expect(page.getByRole("button", { name: "Xóa bộ lọc" })).toBeVisible();
    await expect(page.getByText(/Hiển thị \d+–\d+ \/ \d+ chính sách/)).toBeVisible();

    const firstRowBefore = await page.locator("table tbody tr").first().textContent();
    await page.getByRole("button", { name: /Ngày/ }).click();
    await expect(page).toHaveURL(/sortOrder=(asc|desc)/);
    const firstRowAfter = await page.locator("table tbody tr").first().textContent();
    expect(firstRowBefore).not.toEqual(firstRowAfter);
  });

  test("TC-FR-24-015 TC-FR-25-015 TC-BR-20-015: FRM-07 GPS gating and DC-09 precedence preview", async ({
    page,
  }) => {
    await page.setViewportSize({ width: 1280, height: 720 });
    await loginAcademicAdminPolicies(page);

    await page
      .locator("table tbody tr")
      .filter({ hasText: "SE101-01" })
      .getByRole("button", { name: "Sửa" })
      .click();
    await expect(page.getByTestId("policy-form")).toBeVisible();

    const gpsSwitch = page.getByRole("switch", { name: "Bắt buộc GPS" });
    await gpsSwitch.uncheck();
    await expect(page.getByTestId("gps-radius-input")).toBeDisabled();
    await gpsSwitch.check();
    await expect(page.getByTestId("gps-radius-input")).toBeEnabled();
    await expect(page.getByTestId("gps-radius-input")).toHaveValue("100");

    await expect(page.getByTestId("policy-resolution-summary")).toBeVisible();
    await expect(page.getByRole("list", { name: "Chuỗi ưu tiên chính sách" })).toContainText(
      "Lớp học phần",
    );
    await expect(page.getByRole("button", { name: /Cửa sổ Có mặt.*Lớp học phần/ })).toBeVisible();

    const presentInput = page.getByTestId("present-window-input");
    const priorValue = await presentInput.inputValue();
    const nextValue = priorValue === "30" ? "28" : "30";
    await presentInput.fill(nextValue);
    await expect(
      page.locator('[data-testid="policy-resolution-summary"]').getByText(nextValue).first(),
    ).toBeVisible();

    await page.getByRole("button", { name: "Cập nhật chính sách" }).click();
    await expect(
      page.locator("table tbody tr").filter({ hasText: "SE101-01" }),
    ).toContainText(`${nextValue} /`);
  });

  test("TC-FR-25-016 TC-BR-20-016: lecturer roster shows policy-driven Present and Late badges", async ({
    page,
  }) => {
    const both = await findOpenSessionWithPresentAndLate(page);
    const fixture = both ?? (await findOpenSessionWithLateRows(page));
    test.skip(!fixture, "No open session with Late attendance in preview stack");

    await loginLecturerToRoster(page, fixture!.sessionId);

    await expect(page.getByText("Đang mở")).toBeVisible();
    await expect(page.getByRole("columnheader", { name: "Sinh viên" })).toBeVisible();
    await expect(page.getByRole("columnheader", { name: "Trạng thái" })).toBeVisible();
    await expect(page.locator("tr").filter({ hasText: "Đi trễ" }).first()).toBeVisible();

    if (both) {
      await expect(page.locator("tr", { hasText: both.presentCode })).toContainText("Có mặt");
      await expect(page.locator("tr", { hasText: both.lateCode })).toContainText("Đi trễ");
    }
  });

  test("TC-AC-09-009: student GPS-denied check-in shows recovery and lecturer fallback copy", async ({
    page,
  }) => {
    await page.setViewportSize(STUDENT_PERSONA.viewport);
    const lateFixture = await findOpenSessionWithLateRows(page);
    test.skip(!lateFixture, "No open GPS-required session for check-in");

    const qr = await fetchSessionQr(page, lateFixture!.sessionId);
    await loginViaApi(page, STUDENT_PERSONA.email, STUDENT_PERSONA.password, "/check-in");
    await page.context().clearPermissions();

    await page.goto(`${WEB_BASE_URL}/check-in?token=${qr}`);
    await page.getByRole("button", { name: "Từ chối" }).click();

    await expect(page.getByText("Cần quyền vị trí")).toBeVisible();
    await expect(page.getByText(/giảng viên|thủ công/i)).toBeVisible();
    await expect(page.getByRole("button", { name: "Thử lại" })).toBeVisible();
  });

  test("TC-AC-10-009: student out-of-radius check-in shows recovery guidance", async ({
    page,
  }) => {
    await page.setViewportSize(STUDENT_PERSONA.viewport);
    const lateFixture = await findOpenSessionWithLateRows(page);
    test.skip(!lateFixture, "No open GPS-required session for check-in");

    const qr = await fetchSessionQr(page, lateFixture!.sessionId);
    await loginViaApi(page, "student3@attendly.local", STUDENT_PERSONA.password, "/check-in");
    await page.context().grantPermissions(["geolocation"]);
    await page.context().setGeolocation({ latitude: 10.76408, longitude: 106.660172 });

    await page.goto(`${WEB_BASE_URL}/check-in?token=${qr}`);
    await page.getByRole("button", { name: "Cho phép vị trí" }).click();

    await expect(page.getByText("Ngoài phạm vi lớp")).toBeVisible();
    await expect(page.getByText(/gần phòng học|giảng viên/i)).toBeVisible();
  });

  test("TC-AC-09-010 TC-AC-10-010: lecturer manual correction after GPS rejection", async ({
    page,
  }) => {
    await page.setViewportSize(LECTURER_PERSONA.viewport);
    const lateFixture = await findOpenSessionWithLateRows(page);
    test.skip(!lateFixture, "No open session for lecturer roster fallback");

    await loginLecturerToRoster(page, lateFixture!.sessionId);

    const pendingGpsRow = page
      .locator("tr")
      .filter({ hasText: /Thiếu GPS|Ngoài phạm vi|Từ chối GPS/i })
      .first();
    const hasRejection = (await pendingGpsRow.count()) > 0;
    test.skip(!hasRejection, "No GPS-rejected pending row in preview roster");

    const studentCode = (await pendingGpsRow.locator("td").first().textContent())?.slice(0, 5) ?? "";
    await pendingGpsRow.getByRole("button", { name: "Điều chỉnh" }).click();
    await expect(page.getByRole("dialog")).toBeVisible();
    await page.getByRole("textbox", { name: /Lý do/i }).fill("Xác minh có mặt tại lớp");
    await page.getByRole("button", { name: "Lưu điều chỉnh" }).click();

    await expect(page.locator("tr", { hasText: studentCode })).toContainText(
      /Có mặt \(thủ công\)|Thủ công/,
    );
  });
});
