import { expect, test } from "@playwright/test";
import { WEB_BASE_URL } from "../src/support/constants.js";
import {
  buildMixedEnrollmentCsv,
  loginAcademicAdmin,
  uniqueSectionCode,
  uniqueTermCode,
} from "../src/support/academic-admin.js";
import { loginViaApi } from "../src/support/auth.js";
import { LECTURER_PERSONA, STUDENT_PERSONA } from "../src/support/fixtures.js";

/**
 * Slice: web-academic-admin-academic-setup
 * Source TCs: TC-FR-01-011, TC-FR-04-010, TC-FR-06-012, TC-FR-06-013, TC-AC-07-008
 * Acceptance tags: FR-01, FR-04, FR-06, AC-07
 * Generated by browser test agent — do not hand-edit without re-running gate.
 * Verified via Playwright MCP against live preview stack (web 3007 / api 3001).
 */
test.describe("web-academic-admin-academic-setup", () => {
  test("TC-FR-01-011: admin terms list and FRM-02 create term", async ({ page }) => {
    await page.setViewportSize({ width: 1280, height: 720 });
    await loginAcademicAdmin(page, "/admin/terms");

    await expect(page.getByRole("heading", { name: "Danh sách học kỳ" })).toBeVisible();
    await expect(page.getByRole("table", { name: "Danh sách học kỳ" })).toBeVisible();
    await expect(page.getByRole("columnheader", { name: "Mã học kỳ" })).toBeVisible();
    await expect(page.getByRole("columnheader", { name: "Tên học kỳ" })).toBeVisible();
    await expect(page.getByRole("columnheader", { name: "Trạng thái" })).toBeVisible();

    const termCode = uniqueTermCode();
    await page.getByRole("button", { name: "Tạo học kỳ" }).click();
    await expect(page.getByTestId("term-create-form")).toBeVisible();

    await page.getByRole("textbox", { name: "Mã học kỳ" }).fill(termCode);
    await page.getByRole("textbox", { name: "Tên học kỳ" }).fill(`Học kỳ ${termCode}`);
    await page.getByRole("textbox", { name: "Ngày bắt đầu" }).fill("2026-07-01");
    await page.getByRole("textbox", { name: "Ngày kết thúc" }).fill("2026-12-31");
    await page.locator("form").getByRole("button", { name: "Tạo học kỳ" }).click();

    await expect(page.getByRole("cell", { name: termCode, exact: true })).toBeVisible();
    await expect(page.getByText("Đang hoạt động").first()).toBeVisible();
  });

  test("TC-FR-06-013: admin FRM-04 section create with schedule template", async ({
    page,
  }) => {
    await page.setViewportSize({ width: 1280, height: 720 });
    await loginAcademicAdmin(page, "/admin/class-sections");

    const sectionCode = uniqueSectionCode();
    await page.getByRole("button", { name: "Tạo lớp học phần" }).click();
    const form = page.locator("form").filter({ hasText: "FRM-04" });
    await expect(form).toBeVisible();

    await form.getByPlaceholder("SE101-02").fill(sectionCode);
    await form.locator('select[name="termId"]').selectOption({ index: 1 });
    await form.locator('select[name="courseId"]').selectOption({ index: 1 });
    await form.locator('select[name="defaultRoomId"]').selectOption({ index: 1 });
    await form.locator('select[name="dayOfWeek"]').selectOption("Wednesday");
    await form.locator('input[name="startTime"]').fill("10:30");
    await form.locator('input[name="durationMinutes"]').fill("90");
    await form.getByRole("button", { name: "Tạo lớp học phần" }).click();

    await expect(page.getByText(/Đã sinh \d+ buổi học ở trạng thái Scheduled/)).toBeVisible();
    await expect(page.getByRole("cell", { name: sectionCode, exact: true })).toBeVisible();
  });

  test("TC-FR-04-010: enrollment CSV import shows accepted count and row rejections", async ({
    page,
  }) => {
    await page.setViewportSize({ width: 1280, height: 720 });
    await loginAcademicAdmin(page, "/admin/class-sections");

    const sectionCode = uniqueSectionCode();
    await page.getByRole("button", { name: "Tạo lớp học phần" }).click();
    const form = page.locator("form").filter({ hasText: "FRM-04" });
    await form.getByPlaceholder("SE101-02").fill(sectionCode);
    await form.locator('select[name="termId"]').selectOption({ index: 1 });
    await form.locator('select[name="courseId"]').selectOption({ index: 1 });
    await form.getByRole("button", { name: "Tạo lớp học phần" }).click();
    await expect(page.getByRole("cell", { name: sectionCode, exact: true })).toBeVisible();

    const importLink = page
      .locator("tbody tr")
      .filter({ hasText: sectionCode })
      .getByRole("link", { name: "Nhập đăng ký" });
    await importLink.click();
    await expect(page.getByTestId("enrollment-import-panel")).toBeVisible();

    await page.locator('input[type="file"]').setInputFiles({
      name: "enrollment-mixed.csv",
      mimeType: "text/csv",
      buffer: Buffer.from(buildMixedEnrollmentCsv()),
    });
    await page.getByRole("button", { name: "Nhập danh sách" }).click();

    await expect(page.getByText(/Đã chấp nhận 2 dòng/)).toBeVisible();
    await expect(page.getByText(/từ chối 2 dòng/)).toBeVisible();
    await expect(page.getByRole("table", { name: /Chi tiết lỗi/ })).toBeVisible();
    await expect(page.getByRole("cell", { name: "SV001" }).first()).toBeVisible();
    await expect(page.getByRole("cell", { name: "SV002" })).toBeVisible();
  });

  test("TC-FR-06-012: lecturer PG-04 session list badges and Scheduled filter", async ({
    page,
  }) => {
    await page.setViewportSize(LECTURER_PERSONA.viewport);
    await loginViaApi(
      page,
      LECTURER_PERSONA.email,
      LECTURER_PERSONA.password,
      "/lecturer/sessions",
    );

    await expect(
      page.getByRole("table", { name: "Danh sách buổi học được phân công" }),
    ).toBeVisible();
    await expect(page.getByRole("columnheader", { name: "Trạng thái" })).toBeVisible();

    await page
      .locator('select')
      .filter({ has: page.locator('option[value="Scheduled"]') })
      .selectOption("Scheduled");

    await expect(
      page.getByRole("table", { name: "Danh sách buổi học được phân công" }).or(
        page.getByText("Chưa có buổi học"),
      ),
    ).toBeVisible();
  });

  test("TC-AC-07-008: not-enrolled check-in shows danger alert without retry", async ({
    page,
  }) => {
    await page.setViewportSize(STUDENT_PERSONA.viewport);
    await page.goto(`${WEB_BASE_URL}/check-in?outcome=not-enrolled`);

    await expect(page.getByText("Không thuộc lớp học phần")).toBeVisible();
    await expect(
      page.getByText("Bạn không thuộc lớp học phần này. Nếu bạn nghĩ đây là nhầm lẫn"),
    ).toBeVisible();
    await expect(page.getByRole("button", { name: "Thử lại" })).toHaveCount(0);
    await expect(
      page.getByRole("button", { name: "Xác nhận điểm danh" }),
    ).toHaveCount(0);
  });
});
