import { expect, test } from "@playwright/test";
import { loginViaApi } from "../src/support/auth.js";
import { API_BASE_URL, WEB_BASE_URL } from "../src/support/constants.js";
import {
  ACADEMIC_ADMIN_SEED_EMAIL,
  LECTURER_PERSONA,
  SEED_FIXTURE_IDS,
  STUDENT_PERSONA,
} from "../src/support/fixtures.js";

const SEED_TERM_ID = "20000000-0000-4000-8000-000000000001";
const OUT_OF_SCOPE_SECTION_ID = "00000000-0000-4000-8000-000000000099";

/**
 * Slice: web-academic-admin-reporting-export
 * Source TCs: TC-FR-27-015, TC-FR-27-016, TC-FR-28-017, TC-FR-28-018,
 * TC-BR-18-015, TC-BR-18-016, TC-AC-15-009, TC-AC-16-012, TC-AC-16-013, TC-AC-17-009
 * Generated by browser test agent — do not hand-edit without re-running gate.
 */
test.describe("web-academic-admin-reporting-export", () => {
  test.beforeEach(async ({ page }) => {
    await page.setViewportSize(LECTURER_PERSONA.viewport);
  });

  test("TC-FR-28-017: lecturer filters, searches, sorts, and paginates PG-13 report with URL sync", async ({
    page,
  }) => {
    await loginViaApi(page, LECTURER_PERSONA.email, LECTURER_PERSONA.password, "/reports/attendance");

    await expect(page.getByRole("heading", { name: "Báo cáo điểm danh" })).toBeVisible();
    await expect(page.getByTestId("attendance-report-list")).toBeVisible();

    const sectionOptions = await page.getByLabel("Lọc theo lớp học phần").locator("option").allTextContents();
    expect(sectionOptions).toContain("SE101-01");
    expect(sectionOptions.some((label) => label.includes("SE101-02"))).toBe(false);

    await page.getByLabel("Lọc theo trạng thái điểm danh").selectOption("Absent");
    await expect(page).toHaveURL(/status=Absent/);
    await expect(page.getByText("Vắng").first()).toBeVisible();

    await page.getByLabel("Từ ngày").fill("2026-07-01");
    await page.getByLabel("Đến ngày").fill("2026-07-03");
    await expect(page).toHaveURL(/from=2026-07-01/);
    await expect(page).toHaveURL(/to=2026-07-03/);

    await page.getByLabel("Tìm kiếm danh sách").fill("SV001");
    await expect(page).toHaveURL(/search=SV001/, { timeout: 5_000 });
    await expect(page.getByText("SV001").first()).toBeVisible();

    await page.getByRole("button", { name: /Thứ tự/ }).click();
    await expect(page).toHaveURL(/sortOrder=asc/);

    await page.getByRole("button", { name: "Xóa bộ lọc" }).click();
    await expect(page.getByRole("button", { name: "Trang sau" })).toBeEnabled();
    await page.getByRole("button", { name: "Trang sau" }).click();
    await expect(page).toHaveURL(/page=2/);
    await expect(page.getByText(/Trang 2 \/ \d+/)).toBeVisible();
  });

  test("TC-FR-27-015 TC-BR-18-015 TC-AC-15-009: lecturer scoped CSV export with ExportScopeSummary", async ({
    page,
  }) => {
    await loginViaApi(page, LECTURER_PERSONA.email, LECTURER_PERSONA.password, "/reports/attendance");

    await page
      .getByLabel("Lọc theo lớp học phần")
      .selectOption(SEED_FIXTURE_IDS.section);
    await expect(page).toHaveURL(/classSectionId=/);

    await page.getByRole("button", { name: "Xuất CSV" }).click();
    await expect(page.getByRole("heading", { name: "Xác nhận phạm vi xuất CSV" })).toBeVisible();
    await expect(page.getByText("Giảng viên · chỉ các lớp được phân công")).toBeVisible();
    await expect(page.locator("dt:has-text('Lớp học phần') + dd")).toHaveText("SE101-01");

    const downloadPromise = page.waitForEvent("download");
    await page.getByRole("button", { name: "Xác nhận xuất CSV" }).click();
    await expect(page.getByText("Xuất CSV thành công")).toBeVisible({ timeout: 15_000 });

    const download = await downloadPromise;
    const path = await download.path();
    expect(path).toBeTruthy();
    const csv = await download.createReadStream();
    const chunks: Buffer[] = [];
    if (csv) {
      for await (const chunk of csv) {
        chunks.push(Buffer.from(chunk));
      }
    }
    const content = Buffer.concat(chunks).toString("utf-8");
    expect(content).toContain("studentCode,studentUserId,classSectionId");
    expect(content).toContain(SEED_FIXTURE_IDS.section);
    expect(content).not.toContain(OUT_OF_SCOPE_SECTION_ID);
  });

  test("TC-FR-27-016 TC-BR-18-016 TC-AC-16-012: student blocked from institution report and export", async ({
    page,
  }) => {
    await page.setViewportSize(STUDENT_PERSONA.viewport);
    await loginViaApi(page, STUDENT_PERSONA.email, STUDENT_PERSONA.password, "/reports/attendance");

    await expect(page.getByText("Không có quyền truy cập")).toBeVisible();
    await expect(page.getByRole("table")).toHaveCount(0);
    await expect(page.getByRole("button", { name: "Xuất CSV" })).toHaveCount(0);
    await expect(
      page.getByRole("link", { name: "lịch sử điểm danh cá nhân" }),
    ).toBeVisible();

    const loginRes = await page.request.post(`${API_BASE_URL}/auth/login`, {
      data: { email: STUDENT_PERSONA.email, password: STUDENT_PERSONA.password },
    });
    const token = (await loginRes.json()).data?.accessToken as string;
    const exportRes = await page.request.post(`${API_BASE_URL}/exports/attendance`, {
      headers: {
        Authorization: `Bearer ${token}`,
        "Idempotency-Key": `pw-student-deny-${Date.now()}`,
        "Content-Type": "application/json",
      },
      data: { format: "csv", filters: { termId: SEED_TERM_ID } },
    });
    expect(exportRes.status()).toBe(403);
  });

  test("TC-FR-28-018: listing shows no-results, empty, and student access-denied states", async ({
    page,
  }) => {
    await loginViaApi(page, LECTURER_PERSONA.email, LECTURER_PERSONA.password, "/reports/attendance");

    await page.goto(
      `${WEB_BASE_URL}/reports/attendance?termId=${SEED_TERM_ID}&search=ZZZNOMATCH&status=Excused`,
    );
    await expect(page.getByText("Không tìm thấy kết quả")).toBeVisible();
    await expect(
      page.getByRole("alert").getByRole("button", { name: "Xóa bộ lọc" }),
    ).toBeVisible();

    await page.goto(
      `${WEB_BASE_URL}/reports/attendance?termId=${SEED_TERM_ID}&classSectionId=f0e41570-8fc0-4dc8-a43a-bf0b0f90e34b`,
    );
    await expect(page.getByText("Chưa có dữ liệu báo cáo")).toBeVisible();
    await expect(page.getByRole("table")).toHaveCount(0);

    await page.setViewportSize(STUDENT_PERSONA.viewport);
    await loginViaApi(page, STUDENT_PERSONA.email, STUDENT_PERSONA.password, "/reports/attendance");
    await expect(page.getByText("Không có quyền truy cập")).toBeVisible();
    await expect(page.getByRole("table")).toHaveCount(0);
  });

  test("TC-AC-16-013: lecturer sees denial for tampered out-of-scope classSectionId", async ({
    page,
  }) => {
    await loginViaApi(page, LECTURER_PERSONA.email, LECTURER_PERSONA.password, "/reports/attendance");

    await page.goto(
      `${WEB_BASE_URL}/reports/attendance?classSectionId=${OUT_OF_SCOPE_SECTION_ID}`,
    );
    await expect(page.getByText("Ngoài phạm vi được phép")).toBeVisible();
    await expect(page.getByRole("table")).toHaveCount(0);

    const loginRes = await page.request.post(`${API_BASE_URL}/auth/login`, {
      data: { email: LECTURER_PERSONA.email, password: LECTURER_PERSONA.password },
    });
    const token = (await loginRes.json()).data?.accessToken as string;
    const exportRes = await page.request.post(`${API_BASE_URL}/exports/attendance`, {
      headers: {
        Authorization: `Bearer ${token}`,
        "Idempotency-Key": `pw-oos-deny-${Date.now()}`,
        "Content-Type": "application/json",
      },
      data: {
        format: "csv",
        filters: { termId: SEED_TERM_ID, classSectionId: OUT_OF_SCOPE_SECTION_ID },
      },
    });
    expect(exportRes.status()).toBe(403);
    const body = await exportRes.json();
    expect(body.error?.code).toMatch(/OutOfScope|Forbidden/);
  });

  test("TC-AC-17-009: export completion creates queryable audit log entry", async ({ page }) => {
    await loginViaApi(page, LECTURER_PERSONA.email, LECTURER_PERSONA.password, "/reports/attendance");

    await page
      .getByLabel("Lọc theo lớp học phần")
      .selectOption(SEED_FIXTURE_IDS.section);
    await page.getByRole("button", { name: "Xuất CSV" }).click();
    await page.getByRole("button", { name: "Xác nhận xuất CSV" }).click();
    await expect(page.getByText("Xuất CSV thành công")).toBeVisible({ timeout: 15_000 });

    const adminLogin = await page.request.post(`${API_BASE_URL}/auth/login`, {
      data: { email: ACADEMIC_ADMIN_SEED_EMAIL, password: LECTURER_PERSONA.password },
    });
    const adminToken = (await adminLogin.json()).data?.accessToken as string;
    const auditRes = await page.request.get(
      `${API_BASE_URL}/audit-logs?actionType=Export&page=1&pageSize=5`,
      { headers: { Authorization: `Bearer ${adminToken}` } },
    );
    expect(auditRes.ok()).toBe(true);
    const auditBody = await auditRes.json();
    const exportEntry = auditBody.data?.find(
      (row: { actorUserId: string; format: string }) =>
        row.actorUserId === SEED_FIXTURE_IDS.lecturerUser && row.format === "csv",
    );
    expect(exportEntry).toBeTruthy();
    expect(exportEntry.scopeFilterSummary).toContain(SEED_FIXTURE_IDS.section);
  });
});
