import { expect, test, type Page } from "@playwright/test";
import { loginViaApi } from "../src/support/auth.js";
import { fetchCurrentQrToken } from "../src/support/check-in.js";
import { WEB_BASE_URL } from "../src/support/constants.js";
import { LECTURER_PERSONA, STUDENT_PERSONA } from "../src/support/fixtures.js";

/**
 * Slice: web-lecturer-session-control
 * Source TCs: TC-FR-07-012, TC-FR-14-011, TC-FR-14-012, TC-FR-14-013,
 * TC-AC-01-008, TC-AC-02-010, TC-AC-06-007.
 * Generated by browser test agent — do not hand-edit without re-running gate.
 */
test.describe("web-lecturer-session-control", () => {
  test.beforeEach(async ({ page }) => {
    await page.setViewportSize(LECTURER_PERSONA.viewport);
  });

  test("TC-FR-07-012 TC-AC-01-008: lecturer opens scheduled session and sees QR state", async ({
    page,
  }) => {
    await loginLecturer(page);
    await page.goto(`${WEB_BASE_URL}/lecturer/sessions`);

    const openFromList = page.getByRole("link", { name: "Mở điểm danh" }).first();
    await expect(openFromList).toBeVisible();
    await openFromList.click();

    await expect(page).toHaveURL(/\/lecturer\/sessions\/[0-9a-f-]+$/);
    await expect(page.getByText("Đang mở").first()).toBeVisible();
    await expect(page.getByTestId("qr-display-canvas")).toBeVisible();
    await expect(page.getByText(/Còn \d+ giây/)).toBeVisible();
    await expect(page.getByText(/Lúc mở|opened/i)).toBeVisible();
  });

  test("TC-FR-14-011 TC-FR-14-012 TC-AC-02-010: open QR is projection-sized and rotates", async ({
    page,
  }) => {
    await loginLecturer(page);
    const openedSessionId = await openFirstScheduledOrVisitOpen(page);

    await expect(page.getByText("SE101-01").first()).toBeVisible();
    await expect(page.getByText(/Nhập môn phần mềm/)).toBeVisible();
    await expect(page.getByText("Đang mở").first()).toBeVisible();

    const qr = page.getByTestId("qr-display-canvas");
    await expect(qr).toBeVisible();
    const qrBox = await qr.boundingBox();
    expect(qrBox?.width).toBeGreaterThanOrEqual(400);
    expect(qrBox?.height).toBeGreaterThanOrEqual(400);

    await expect(page.getByText(/A101|Phòng|Thứ/)).toBeVisible();

    const initialQr = await qr.evaluate((node) => node.outerHTML);
    await expect
      .poll(async () => qr.evaluate((node) => node.outerHTML), {
        timeout: 35_000,
      })
      .not.toBe(initialQr);

    await expect(page).toHaveURL(
      new RegExp(`/lecturer/sessions/${openedSessionId}$`),
    );
    await expect(page.getByText("Đang mở").first()).toBeVisible();
  });

  test("TC-FR-14-013: closed session hides QR and shows locked state", async ({
    page,
  }) => {
    await loginLecturer(page);
    await page.goto(`${WEB_BASE_URL}/lecturer/sessions`);

    const closedRow = page.locator("tbody tr").filter({ hasText: "Đã đóng" }).first();
    await expect(closedRow).toBeVisible();
    await closedRow.getByRole("link", { name: "Chi tiết" }).click();

    await expect(page.getByText("Đã đóng").first()).toBeVisible();
    await expect(page.getByText(/mã QR không còn hiệu lực/)).toBeVisible();
    await expect(page.getByTestId("qr-display-canvas")).toHaveCount(0);
    await expect(page.getByText(/Còn \d+ giây/)).toHaveCount(0);
    await expect(page.getByRole("button", { name: "Làm mới mã QR" })).toBeDisabled();
  });

  test("TC-AC-06-007: unauthenticated student returns to check-in after login", async ({
    page,
  }) => {
    const openedSessionId = await prepareOpenSessionId(page);
    const qrPayload = await fetchCurrentQrToken(page, openedSessionId);

    await page.context().clearCookies();
    await page.goto(`${WEB_BASE_URL}/check-in?token=${qrPayload}`);
    await page.evaluate(() => {
      localStorage.clear();
      sessionStorage.clear();
    });
    await page.reload();

    await expect(page).toHaveURL(/\/login\?returnUrl=.*check-in.*token/);
    await expect(page.getByText(/Đăng nhập để tiếp tục/)).toBeVisible();

    await page.getByRole("textbox", { name: "Mã sinh viên" }).fill("SV001");
    await page
      .getByRole("textbox", { name: "Mật khẩu" })
      .fill(STUDENT_PERSONA.password);
    await page.getByRole("button", { name: "Đăng nhập" }).click();

    await expect(page).toHaveURL(new RegExp(`/check-in\\?token=${qrPayload}`));
    await page.getByRole("button", { name: "Cho phép vị trí" }).click();
    await page.getByRole("button", { name: "Xác nhận điểm danh" }).click();

    await expect(page.getByText(/Điểm danh thành công/)).toBeVisible();
    await expect(page.getByText(/Có mặt|Đi trễ/)).toBeVisible();
  });
});

async function loginLecturer(page: Page): Promise<void> {
  await loginViaApi(
    page,
    LECTURER_PERSONA.email,
    LECTURER_PERSONA.password,
    "/lecturer/sessions",
  );
}

async function openFirstScheduledOrVisitOpen(page: Page): Promise<string> {
  await page.goto(`${WEB_BASE_URL}/lecturer/sessions`);
  const openFromList = page.getByRole("link", { name: "Mở điểm danh" }).first();
  if ((await openFromList.count()) > 0) {
    await openFromList.click();
  } else {
    const openRow = page.locator("tbody tr").filter({ hasText: "Đang mở" }).first();
    await expect(openRow).toBeVisible();
    await openRow.getByRole("link", { name: "Chi tiết" }).click();
  }

  await expect(page).toHaveURL(/\/lecturer\/sessions\/[0-9a-f-]+$/);
  return page.url().split("/").pop() ?? "";
}

async function prepareOpenSessionId(page: Page): Promise<string> {
  await loginLecturer(page);
  return openFirstScheduledOrVisitOpen(page);
}
