import { expect, test } from "@playwright/test";
import { WEB_BASE_URL } from "../src/support/constants.js";
import { SEED_FIXTURE_IDS, STUDENT_PERSONA } from "../src/support/fixtures.js";
import {
  expectButtonMinSize,
  fetchCurrentQrToken,
  loginStudentMobile,
  openSeedSessionAndFetchQr,
} from "../src/support/check-in.js";

/**
 * Slice: web-student-check-in-flow
 * Source TCs: TC-FR-15-008, TC-FR-16-010, TC-FR-16-011, TC-FR-23-012,
 * TC-AC-06-007, TC-AC-11-010, TC-NFR-14-009 through TC-NFR-14-014.
 * Generated by browser test agent — do not hand-edit without re-running gate.
 */
test.describe("web-student-check-in-flow", () => {
  test.beforeEach(async ({ page }) => {
    await page.setViewportSize(STUDENT_PERSONA.viewport);
  });

  test("TC-FR-15-008 TC-AC-06-007 TC-NFR-14-010: login gate preserves token and enables check-in", async ({
    page,
  }) => {
    const qrPayload = await fetchCurrentQrToken(
      page,
      SEED_FIXTURE_IDS.scheduledSession,
    );
    await page.context().clearCookies();
    await page.evaluate(() => {
      localStorage.clear();
      sessionStorage.clear();
    });

    await page.goto(`${WEB_BASE_URL}/check-in?token=${qrPayload}`);

    await expect(page).toHaveURL(/\/login/);
    await expect(page).toHaveURL(/returnUrl=.*check-in.*token/);
    await expect(page.getByText(/Đăng nhập để tiếp tục/)).toBeVisible();

    await page.getByRole("textbox", { name: "Mã sinh viên" }).fill("SV001");
    await page
      .getByRole("textbox", { name: "Mật khẩu" })
      .fill(STUDENT_PERSONA.password);
    await page.getByRole("button", { name: "Đăng nhập" }).click();

    await expect(page).toHaveURL(new RegExp(`/check-in\\?token=${qrPayload}`));
    await expect(
      page.getByRole("button", { name: "Xác nhận điểm danh" }),
    ).toBeVisible();
  });

  test("TC-FR-16-010: mobile deep link check-in renders success-present with timestamp", async ({
    page,
  }) => {
    const { qrPayload } = await openSeedSessionAndFetchQr(page);
    await loginStudentMobile(page);

    const context = page.context();
    await context.grantPermissions(["geolocation"]);
    await context.setGeolocation({
      latitude: 10.762622,
      longitude: 106.660172,
      accuracy: 10,
    });

    await page.goto(`${WEB_BASE_URL}/check-in?token=${qrPayload}`);
    await page.getByRole("button", { name: "Cho phép vị trí" }).click();
    await page.getByRole("button", { name: "Xác nhận điểm danh" }).click();

    await expect(
      page
        .getByRole("status")
        .or(page.getByText(/Điểm danh thành công/))
        .or(page.getByText("Bạn đã điểm danh buổi học này rồi.")),
    ).toBeVisible();
    await expect(page.getByText(/Có mặt|Đi trễ/)).toBeVisible();
  });

  test("TC-FR-16-011 TC-NFR-14-009: expired QR shows Vietnamese rescan guidance with retry", async ({
    page,
  }) => {
    await loginStudentMobile(page);
    const staleToken = "611776e0-10c5-48fb-9a2b-7162f02dd5f7";

    await page.goto(`${WEB_BASE_URL}/check-in?token=${staleToken}`);
    await page.getByRole("button", { name: "Cho phép vị trí" }).click().catch(() => {});
    await page.getByRole("button", { name: "Xác nhận điểm danh" }).click();

    await expect(page.getByText("Mã QR đã hết hạn")).toBeVisible();
    const retry = page.getByRole("button", { name: "Thử lại" });
    await expect(retry).toBeVisible();
    await expectButtonMinSize(retry, 44);
    await retry.click();

    const fresh = await fetchCurrentQrToken(
      page,
      SEED_FIXTURE_IDS.scheduledSession,
    );
    await page.goto(`${WEB_BASE_URL}/check-in?token=${fresh}`);
    await expect(
      page.getByRole("button", { name: "Xác nhận điểm danh" }),
    ).toBeVisible();
  });

  test("TC-FR-23-012 TC-AC-11-010: success-present and success-late outcome screens", async ({
    page,
  }) => {
    await page.goto(`${WEB_BASE_URL}/check-in?outcome=success-present`);
    const present = page.getByRole("status");
    await expect(present).toContainText(/Điểm danh thành công.*Có mặt/);
    await expect(present.getByText("Có mặt")).toBeVisible();
    await expect(present).toContainText("Lúc");

    await page.goto(`${WEB_BASE_URL}/check-in?outcome=success-late`);
    const late = page.getByRole("status");
    await expect(late).toContainText(/Điểm danh thành công.*Đi trễ/);
    await expect(late.getByText("Đi trễ")).toBeVisible();
    await expect(late).toContainText("Lúc");
  });

  test("TC-NFR-14-011: GPS denied preview shows Vietnamese location guidance", async ({
    page,
  }) => {
    await page.goto(`${WEB_BASE_URL}/check-in?outcome=form`);
    await page.getByRole("button", { name: "Từ chối" }).click();

    await expect(page.getByText("Cần quyền vị trí")).toBeVisible();
    await expect(page.getByText(/giảng viên|thủ công/i)).toBeVisible();
  });

  test("TC-NFR-14-012: out-of-radius preview shows Vietnamese recovery guidance", async ({
    page,
  }) => {
    await page.goto(`${WEB_BASE_URL}/check-in?outcome=out-of-radius`);
    await expect(page.getByText("Ngoài phạm vi lớp")).toBeVisible();
    await expect(page.getByText(/gần phòng học|giảng viên/i)).toBeVisible();
  });

  test("TC-NFR-14-013: duplicate check-in shows info alert without retry CTA", async ({
    page,
  }) => {
    await loginStudentMobile(page);
    const qrPayload = await fetchCurrentQrToken(
      page,
      SEED_FIXTURE_IDS.scheduledSession,
    );

    await page.goto(`${WEB_BASE_URL}/check-in?token=${qrPayload}`);
    await page.getByRole("button", { name: "Cho phép vị trí" }).click().catch(() => {});
    await page.getByRole("button", { name: "Xác nhận điểm danh" }).click();

    await expect(
      page.getByText("Bạn đã điểm danh buổi học này rồi."),
    ).toBeVisible();
    await expect(page.getByRole("button", { name: "Thử lại" })).toHaveCount(0);
    await expect(
      page.getByRole("button", { name: "Xác nhận điểm danh" }),
    ).toHaveCount(0);
  });

  test("TC-NFR-14-014: mobile check-in controls meet 44px touch targets", async ({
    page,
  }) => {
    await loginStudentMobile(page);
    const qrPayload = await fetchCurrentQrToken(
      page,
      SEED_FIXTURE_IDS.scheduledSession,
    );
    await page.goto(`${WEB_BASE_URL}/check-in?token=${qrPayload}`);

    await expectButtonMinSize(
      page.getByRole("button", { name: "Cho phép vị trí" }),
      44,
    );
    await expectButtonMinSize(page.getByRole("button", { name: "Từ chối" }), 44);
    await expectButtonMinSize(
      page.getByRole("button", { name: "Xác nhận điểm danh" }),
      44,
    );

    const horizontalScroll = await page.evaluate(
      () =>
        document.documentElement.scrollWidth >
        document.documentElement.clientWidth,
    );
    expect(horizontalScroll).toBe(false);
  });
});
