import { expect, test } from "@playwright/test";
import { WEB_BASE_URL } from "../src/support/constants.js";

/**
 * Slice: web-design-system-shell
 * Source TCs: TC-FR-14-011, TC-FR-14-012, TC-FR-14-013,
 * TC-NFR-14-009, TC-NFR-14-010, TC-NFR-14-011, TC-NFR-14-012,
 * TC-NFR-14-013, TC-NFR-14-014, TC-NFR-15-010, TC-NFR-15-011,
 * TC-NFR-15-012, TC-NFR-15-013, TC-NFR-15-014.
 * Generated by browser test agent — do not hand-edit without re-running gate.
 */
test.describe("web-design-system-shell", () => {
  test("design system showcase exposes tokenized primitives and route shells", async ({
    page,
  }) => {
    await page.goto(`${WEB_BASE_URL}/showcase`);

    await expect(
      page.getByRole("heading", { name: "Attendly Design System" }),
    ).toBeVisible();
    await expect(page.getByRole("button", { name: "Brand" })).toBeVisible();
    await expect(page.getByRole("button", { name: "Disabled" })).toBeDisabled();
    await expect(page.getByText("Thành công")).toBeVisible();
    await expect(page.getByText("Đang mở")).toBeVisible();
    await expect(
      page.getByRole("link", { name: "PG-05 · QrDisplayPanel (Open)" }),
    ).toBeVisible();
  });

  test("PG-05 open QR projection displays identity, countdown, and rotates", async ({
    page,
  }) => {
    await page.setViewportSize({ width: 1200, height: 800 });
    await page.goto(`${WEB_BASE_URL}/lecturer/sessions/demo-open`);

    await expect(page.getByRole("heading", { name: "Mã QR điểm danh" })).toBeVisible();
    await expect(page.getByText("CSE101-A").first()).toBeVisible();
    await expect(page.getByText(/Lập trình Web.*Buổi 05/)).toBeVisible();
    await expect(page.getByText("Đang mở").first()).toBeVisible();
    await expect(page.getByText(/Còn \d+ giây/)).toBeVisible();

    const qr = page.getByTestId("qr-display-canvas");
    await expect(qr).toBeVisible();
    const qrBox = await qr.boundingBox();
    expect(qrBox?.width).toBeGreaterThanOrEqual(400);
    expect(qrBox?.height).toBeGreaterThanOrEqual(400);

    const initialRotation = await readTokenRotation(page);
    await expect
      .poll(() => readTokenRotation(page), { timeout: 35_000 })
      .toBeGreaterThan(initialRotation);

    const warningState = await waitForCountdownWarning(page);
    expect(warningState.seconds).toBeLessThanOrEqual(5);
    expect(warningState.stroke).not.toBe("rgb(255, 219, 51)");
  });

  test("PG-05 closed QR state hides active QR and countdown", async ({ page }) => {
    await page.setViewportSize({ width: 1280, height: 720 });
    await page.goto(`${WEB_BASE_URL}/lecturer/sessions/demo-closed`);

    await expect(page.getByText("Đã đóng").first()).toBeVisible();
    await expect(
      page.getByText(/Buổi học đã đóng.*mã QR không còn hiệu lực/),
    ).toBeVisible();
    await expect(page.getByTestId("qr-display-canvas")).toHaveCount(0);
    await expect(page.getByText(/Còn \d+ giây/)).toHaveCount(0);
  });

  test("PG-02 mobile outcome states render Vietnamese guidance and recovery", async ({
    page,
  }) => {
    await page.setViewportSize({ width: 375, height: 812 });

    await page.goto(`${WEB_BASE_URL}/check-in?outcome=expired-qr`);
    await expect(page.getByText("Mã QR đã hết hạn")).toBeVisible();
    const retry = page.getByRole("button", { name: "Thử lại" });
    await expect(retry).toBeVisible();
    await expectButtonMinSize(retry, 44);
    await retry.click();
    await expect(page).toHaveURL(/outcome=form/);

    const allowLocation = page.getByRole("button", { name: "Cho phép vị trí" });
    const denyLocation = page.getByRole("button", { name: "Từ chối" });
    const submit = page.getByRole("button", { name: "Xác nhận điểm danh" });
    await expectButtonMinSize(allowLocation, 44);
    await expectButtonMinSize(denyLocation, 44);
    await expectButtonMinSize(submit, 44);

    await allowLocation.click();
    await expect(page.getByText(/Điểm danh thành công.*Có mặt/)).toBeVisible();
    await expect(page.getByText("Lúc 08:02")).toBeVisible();

    await page.goto(`${WEB_BASE_URL}/check-in?outcome=gps-denied`);
    await expect(page.getByText("Cần quyền vị trí")).toBeVisible();
    await expect(page.getByText(/báo giảng viên hỗ trợ thủ công/i)).toBeVisible();

    await page.goto(`${WEB_BASE_URL}/check-in?outcome=out-of-radius`);
    await expect(page.getByText("Ngoài phạm vi lớp")).toBeVisible();
    await expect(page.getByText(/đến gần phòng học|liên hệ giảng viên/i)).toBeVisible();

    await page.goto(`${WEB_BASE_URL}/check-in?outcome=duplicate`);
    await expect(page.getByText("Bạn đã điểm danh buổi học này rồi.")).toBeVisible();
    await expect(page.getByText("Có mặt")).toBeVisible();
    await expect(page.getByRole("button", { name: /Thử lại|Xác nhận điểm danh/ })).toHaveCount(0);
  });

  test("PG-02 unauthenticated token deep link redirects to login with return URL", async ({
    page,
  }) => {
    await page.setViewportSize({ width: 375, height: 812 });
    await page.goto(`${WEB_BASE_URL}/check-in?token=validToken`);

    await expect(page).toHaveURL(/\/login/);
    await expect(page).toHaveURL(/returnUrl=.*check-in.*token/);
    await expect(page.getByText(/Đăng nhập để tiếp tục/)).toBeVisible();

    await page.getByRole("textbox", { name: "Mã sinh viên" }).fill("SV001");
    await page.getByRole("textbox", { name: "Mật khẩu" }).fill("test");
    await page.getByRole("button", { name: "Đăng nhập" }).click();

    await expect(page).toHaveURL(/\/check-in\?token=validToken/);
    await expect(
      page.getByRole("button", { name: "Xác nhận điểm danh" }),
    ).toBeVisible();
  });

  test("PG-05 projector viewport keeps QR and state indicators unclipped", async ({
    page,
  }) => {
    await page.setViewportSize({ width: 1280, height: 720 });
    await page.goto(`${WEB_BASE_URL}/lecturer/sessions/demo-open`);

    const qr = page.getByTestId("qr-display-canvas");
    await expect(qr).toBeVisible();
    const qrBox = await qr.boundingBox();
    expect(qrBox).not.toBeNull();
    expect(qrBox!.height).toBeGreaterThanOrEqual(720 * 0.6);
    expect(qrBox!.y + qrBox!.height).toBeLessThanOrEqual(720);

    await expect(page.getByText("CSE101-A").first()).toBeVisible();
    await expect(page.getByText(/Lập trình Web.*Buổi 05/)).toBeVisible();
    await expect(page.getByText("Đang mở").first()).toBeVisible();
    await expect(page.getByText(/Còn \d+ giây/)).toBeVisible();
    expect(
      await page.evaluate(
        () => document.documentElement.scrollWidth > document.documentElement.clientWidth,
      ),
    ).toBe(false);
  });
});

async function readTokenRotation(page: import("@playwright/test").Page): Promise<number> {
  return page.evaluate(() => {
    const match = document.body.innerText.match(/Token rotation #(\d+)/);
    return Number(match?.[1] ?? 0);
  });
}

async function waitForCountdownWarning(
  page: import("@playwright/test").Page,
): Promise<{ seconds: number; stroke: string }> {
  return page.evaluate(async () => {
    const read = () => {
      const seconds = Number(
        document.body.innerText.match(/(\d+)s\s*\nCòn \1 giây/)?.[1] ?? Number.NaN,
      );
      const progress = document.querySelector('circle[class*="progress"]');
      return {
        seconds,
        stroke: progress ? getComputedStyle(progress).stroke : "",
      };
    };

    const deadline = Date.now() + 35_000;
    let state = read();
    while (Date.now() < deadline && !(Number.isFinite(state.seconds) && state.seconds <= 5)) {
      await new Promise((resolve) => setTimeout(resolve, 250));
      state = read();
    }
    return state;
  });
}

async function expectButtonMinSize(
  locator: import("@playwright/test").Locator,
  minSize: number,
): Promise<void> {
  const box = await locator.boundingBox();
  expect(box).not.toBeNull();
  expect(box!.width).toBeGreaterThanOrEqual(minSize);
  expect(box!.height).toBeGreaterThanOrEqual(minSize);
}
