import { expect, test } from "@playwright/test";
import { loginViaApi } from "../src/support/auth.js";
import { WEB_BASE_URL } from "../src/support/constants.js";
import { LECTURER_PERSONA, STUDENT_PERSONA } from "../src/support/fixtures.js";
import {
  fetchCurrentQr,
  findClosedSessionWithAbsent,
  findOpenSessionWithPending,
  findOpenSessionWithRejectedAttempt,
  loginLecturerToRoster,
  submitStudentCheckIn,
} from "../src/support/roster.js";

/**
 * Slice: web-lecturer-live-roster-fallback
 * Source TCs: TC-FR-19-012, TC-FR-19-013, TC-FR-19-014, TC-FR-20-015,
 * TC-BR-14-009, TC-BR-14-010, TC-AC-13-011, TC-AC-14-010, TC-AC-25-011, TC-AC-25-012.
 * Generated by browser test agent — do not hand-edit without re-running gate.
 */
test.describe("web-lecturer-live-roster-fallback", () => {
  test("TC-FR-19-012: live roster summary chips and realtime row updates", async ({
    page,
  }) => {
    const fixture = await findOpenSessionWithPending(page);
    test.skip(!fixture, "No open session with pending student in preview stack");

    await loginLecturerToRoster(page, fixture!.sessionId);
    await expect(page.getByTestId("live-roster-panel")).toBeVisible();
    await expect(page.getByText("Có mặt")).toBeVisible();
    await expect(page.getByText("Muộn")).toBeVisible();
    await expect(page.getByText("Chưa điểm danh")).toBeVisible();
    await expect(page.getByText("Lần thử lỗi")).toBeVisible();
    await expect(page.getByRole("columnheader", { name: "Sinh viên" })).toBeVisible();
    await expect(page.getByRole("columnheader", { name: "Trạng thái" })).toBeVisible();
    await expect(page.getByRole("columnheader", { name: "Lần thử gần nhất" })).toBeVisible();
    await expect(page.getByText("Cập nhật theo thời gian thực")).toBeVisible();

    const pendingChip = page
      .locator('[aria-label="Tóm tắt điểm danh"]')
      .getByText("Chưa điểm danh")
      .locator("..")
      .locator("span")
      .last();
    const before = Number((await pendingChip.textContent()) ?? "0");

    await submitStudentCheckIn(page, {
      sessionId: fixture!.sessionId,
      studentEmail: `student${fixture!.row.studentCode.replace(/^SV0*/, "")}@attendly.local`,
      gps: { latitude: 10.762622, longitude: 106.660172, accuracyMeters: 10 },
    });

    await expect(pendingChip).not.toHaveText(String(before), { timeout: 15_000 });
    await expect(
      page.locator("tr", { hasText: fixture!.row.studentCode }),
    ).not.toContainText("Chưa điểm danh");
  });

  test("TC-FR-19-013: rejected attempt row shows reason badge and tooltip", async ({
    page,
  }) => {
    const fixture = await findOpenSessionWithRejectedAttempt(page);
    test.skip(!fixture, "No open session with rejected attempt in preview stack");

    await loginLecturerToRoster(page, fixture!.sessionId);
    const badge = page
      .locator("tr", { hasText: fixture!.row.studentCode })
      .locator('[title]')
      .first();
    await expect(badge).toBeVisible();
    const title = await badge.getAttribute("title");
    expect(title).toBeTruthy();
    await expect(page.getByText("Lần thử lỗi")).toBeVisible();
  });

  test("TC-FR-19-014: closed session shows finalized roster without live banner", async ({
    page,
  }) => {
    const fixture = await findClosedSessionWithAbsent(page);
    test.skip(!fixture, "No closed session with absent students in preview stack");

    await loginLecturerToRoster(page, fixture!.sessionId);
    await expect(page.getByText("Đã đóng").first()).toBeVisible();
    await expect(page.getByText("Vắng").first()).toBeVisible();
    await expect(page.getByText("Cập nhật theo thời gian thực")).toHaveCount(0);
    await expect(
      page
        .locator('[aria-label="Tóm tắt điểm danh"]')
        .getByText("Chưa điểm danh")
        .locator("..")
        .locator("span")
        .last(),
    ).toHaveText("0");
  });

  test("TC-FR-20-015 TC-AC-13-011 TC-BR-14-009: manual correction gates reason and updates badge", async ({
    page,
  }) => {
    const fixture = await findClosedSessionWithAbsent(page);
    test.skip(!fixture, "No closed session with absent students in preview stack");

    await loginLecturerToRoster(page, fixture!.sessionId);
    const row = page.locator("tr", { hasText: fixture!.row.studentCode });
    await row.getByRole("button", { name: "Điều chỉnh" }).click();
    await expect(page.getByTestId("manual-correction-dialog")).toBeVisible();

    const save = page.getByRole("button", { name: "Lưu điều chỉnh" });
    await expect(save).toBeDisabled();

    await page.getByLabel("Lý do").fill("ngắn");
    await expect(save).toBeDisabled();

    await page
      .getByLabel("Lý do")
      .fill("Sinh viên có mặt nhưng thiết bị lỗi GPS khi điểm danh.");
    await expect(save).toBeEnabled();
    await save.click();

    await expect(page.getByTestId("manual-correction-dialog")).toHaveCount(0);
    await expect(row.getByText("Có mặt (thủ công)")).toBeVisible();
  });

  test("TC-AC-14-010 TC-BR-14-010: edit window expired shows escalation guidance", async ({
    page,
  }) => {
    const fixture = await findClosedSessionWithAbsent(page);
    test.skip(!fixture, "No closed session with absent students in preview stack");

    await page.route(
      `**/api/v1/class-sessions/${fixture!.sessionId}/attendance/${fixture!.row.studentUserId}`,
      async (route) => {
        if (route.request().method() === "PATCH") {
          await route.fulfill({
            status: 409,
            contentType: "application/json",
            body: JSON.stringify({
              data: null,
              meta: { requestId: "playwright", timestamp: new Date().toISOString() },
              error: {
                code: "EditWindowExpired",
                message: "Manual edit window has expired.",
              },
            }),
          });
          return;
        }
        await route.continue();
      },
    );

    await loginLecturerToRoster(page, fixture!.sessionId);
    const row = page.locator("tr", { hasText: fixture!.row.studentCode });
    await row.getByRole("button", { name: "Điều chỉnh" }).click();
    await page
      .getByLabel("Lý do")
      .fill("Sinh viên có mặt sau khi xác minh trực tiếp tại lớp.");
    await page.getByRole("button", { name: "Lưu điều chỉnh" }).click();

    await expect(page.getByText("Hết thời gian chỉnh sửa")).toBeVisible();
    await expect(page.getByText(/Quản trị học vụ/)).toBeVisible();
    await expect(row.getByText("Vắng")).toBeVisible();
  });

  test("TC-AC-25-011: lecturer resolves pending student via manual correction", async ({
    page,
  }) => {
    const fixture = await findOpenSessionWithPending(page);
    test.skip(!fixture, "No open session with pending student in preview stack");

    await loginLecturerToRoster(page, fixture!.sessionId);
    const row = page.locator("tr", { hasText: fixture!.row.studentCode });
    await row.getByRole("button", { name: "Điều chỉnh" }).click();
    await page
      .getByLabel("Lý do")
      .fill("Xác minh trực tiếp: thiết bị sinh viên không cấp GPS.");
    await page.getByRole("button", { name: "Lưu điều chỉnh" }).click();

    await expect(page.getByTestId("manual-correction-dialog")).toHaveCount(0);
    await expect(row.getByText("Có mặt (thủ công)")).toBeVisible();
  });

  test("TC-AC-25-012: student GPS denial surfaces fallback guidance and lecturer affordance", async ({
    page,
  }) => {
    const fixture = await findOpenSessionWithPending(page);
    test.skip(!fixture, "No open session with pending student in preview stack");

    const qr = await fetchCurrentQr(page, fixture!.sessionId);
    await page.setViewportSize(STUDENT_PERSONA.viewport);
    await loginViaApi(
      page,
      STUDENT_PERSONA.email,
      STUDENT_PERSONA.password,
      `/check-in?token=${qr}`,
    );
    await page.context().clearPermissions();
    await page.getByRole("button", { name: "Từ chối" }).click();
    await expect(page.getByText("Cần quyền vị trí")).toBeVisible();
    await expect(page.getByText(/giảng viên|thủ công/i)).toBeVisible();

    await page.setViewportSize(LECTURER_PERSONA.viewport);
    await loginLecturerToRoster(page, fixture!.sessionId);
    const row = page.locator("tr", { hasText: fixture!.row.studentCode });
    await expect(row.getByText("Chưa điểm danh")).toBeVisible();
    await expect(row.getByRole("button", { name: "Điều chỉnh" })).toBeVisible();
  });
});
