import { expect, test } from "@playwright/test";
import { loginViaApi } from "../src/support/auth.js";
import { API_BASE_URL, WEB_BASE_URL } from "../src/support/constants.js";
import {
  ACADEMIC_ADMIN_SEED_EMAIL,
  LECTURER_PERSONA,
  SEED_FIXTURE_IDS,
  STUDENT_PERSONA,
} from "../src/support/fixtures.js";

const SYSTEM_AUDITOR_SEED_EMAIL = "system-auditor@attendly.local";

const SEED_TERM_ID = "20000000-0000-4000-8000-000000000001";
const OUT_OF_SCOPE_SECTION_ID = "00000000-0000-4000-8000-000000000099";
const DISPUTE_SESSION_ID = "70000000-0000-4000-8000-000000000001";

/**
 * Slice: web-system-auditor-audit-review
 * Source TCs: TC-FR-32-014, TC-FR-32-015, TC-FR-30-018, TC-FR-30-019,
 * TC-BR-22-016, TC-AC-19-013, TC-AC-16-012, TC-AC-16-013
 * Generated by browser test agent — do not hand-edit without re-running gate.
 */
test.describe("web-system-auditor-audit-review", () => {
  test.beforeEach(async ({ page }) => {
    await page.setViewportSize(LECTURER_PERSONA.viewport);
  });

  test("TC-FR-32-014: SystemAuditor PG-15 audit logs filter, sort, pagination, read-only detail", async ({
    page,
  }) => {
    await loginViaApi(
      page,
      SYSTEM_AUDITOR_SEED_EMAIL,
      LECTURER_PERSONA.password,
      "/audit/logs",
    );

    await expect(page.getByRole("heading", { name: "Nhật ký audit" })).toBeVisible();
    await expect(page.getByText("Chế độ chỉ đọc · SystemAuditor")).toBeVisible();
    await expect(page.getByTestId("audit-log-list")).toBeVisible();
    await expect(page.getByRole("button", { name: /Thứ tự ↓/ })).toBeVisible();

    await page.getByLabel("Lọc theo người thực hiện").selectOption(SEED_FIXTURE_IDS.lecturerUser);
    await expect(page).toHaveURL(/actorUserId=/);

    await page.getByLabel("Lọc theo loại hành động").selectOption("Export");
    await expect(page).toHaveURL(/actionType=Export/);

    await page.getByLabel("Từ ngày").fill("2026-07-01");
    await page.getByLabel("Đến ngày").fill("2026-07-03");
    await expect(page).toHaveURL(/from=2026-07-01/);
    await expect(page).toHaveURL(/to=2026-07-03/);

    await page.goto(`${WEB_BASE_URL}/audit/logs`);
    await expect(page.getByRole("button", { name: "Trang sau" })).toBeEnabled();
    await page.getByRole("button", { name: "Trang sau" }).click();
    await expect(page).toHaveURL(/page=2/);
    await expect(page.getByText(/Trang 2 \/ \d+/)).toBeVisible();

    await page.goto(
      `${WEB_BASE_URL}/audit/logs?actionType=manual_update&targetType=AttendanceRecord`,
    );
    await page.locator("article button").first().click();
    await expect(page.locator("article button").first()).toHaveAttribute("aria-expanded", "true");
    await expect(page.getByText("Chế độ chỉ đọc — không có thao tác chỉnh sửa hoặc xóa")).toBeVisible();
    await expect(page.getByRole("button", { name: /Sửa|Xóa/i })).toHaveCount(0);
  });

  test("TC-FR-32-015: SystemAuditor dispute evidence on PG-13 and read-only roster", async ({
    page,
  }) => {
    await loginViaApi(
      page,
      SYSTEM_AUDITOR_SEED_EMAIL,
      LECTURER_PERSONA.password,
      "/reports/attendance",
    );

    await expect(page.getByRole("heading", { name: "Báo cáo điểm danh" })).toBeVisible();
    await expect(page.getByRole("button", { name: "Xuất CSV" })).toHaveCount(0);

    await page.getByLabel("Tìm kiếm danh sách").fill("SV001");
    await expect(page).toHaveURL(/search=SV001/, { timeout: 5_000 });
    await expect(page.getByText("Vắng").first()).toBeVisible();

    const auditLink = page.locator("table a", { hasText: "Audit" }).first();
    await expect(auditLink).toHaveAttribute("href", /targetId=/);
    await auditLink.click();
    await expect(page).toHaveURL(/\/audit\/logs\?targetId=/);
    await expect(page.getByTestId("audit-log-list")).toBeVisible();

    await page.goto(`${WEB_BASE_URL}/reports/attendance?search=SV001&status=Absent`);
    await page.locator("table a", { hasText: "Danh sách buổi học" }).first().click();
    await expect(page).toHaveURL(new RegExp(`/audit/sessions/${DISPUTE_SESSION_ID}/roster`));
    await expect(page.getByText("Chỉ đọc · không có thao tác điều chỉnh")).toBeVisible();
    await expect(page.getByRole("button", { name: /Chỉnh sửa|Xuất CSV|Mở buổi|Đóng buổi/i })).toHaveCount(
      0,
    );

    await page.goto(
      `${WEB_BASE_URL}/lecturer/sessions/${DISPUTE_SESSION_ID}/roster`,
    );
    await expect(page.getByText(/Không có quyền|Không thể tải/i)).toBeVisible();
  });

  test("TC-FR-30-018 TC-FR-30-019: lecturer export and SystemAuditor export audit review", async ({
    page,
  }) => {
    await loginViaApi(page, LECTURER_PERSONA.email, LECTURER_PERSONA.password, "/reports/attendance");

    await page.getByLabel("Lọc theo lớp học phần").selectOption(SEED_FIXTURE_IDS.section);
    await page.getByRole("button", { name: "Xuất CSV" }).click();
    await page.getByRole("button", { name: "Xác nhận xuất CSV" }).click();
    await expect(page.getByText("Xuất CSV thành công")).toBeVisible({ timeout: 15_000 });

    await loginViaApi(
      page,
      SYSTEM_AUDITOR_SEED_EMAIL,
      LECTURER_PERSONA.password,
      "/audit/logs?actionType=Export&from=2026-07-01&to=2026-07-03",
    );

    await expect(page.getByText("Nguyễn Văn Giảng").first()).toBeVisible();
    await expect(page.getByText(/csv · termId=/).first()).toBeVisible();
    await page.locator("article button").first().click();
    await expect(page.getByText("CORRELATION", { exact: false })).toBeVisible();
    await expect(page.getByText("PHẠM VI", { exact: false })).toBeVisible();
    await expect(page.getByText("Định dạng", { exact: false })).toBeVisible();
  });

  test("TC-BR-22-016: SystemAuditor attendance mutation audit with old/new status", async ({
    page,
  }) => {
    await loginViaApi(
      page,
      SYSTEM_AUDITOR_SEED_EMAIL,
      LECTURER_PERSONA.password,
      "/audit/logs?targetType=AttendanceRecord&actionType=manual_update&from=2026-07-01&to=2026-07-03",
    );

    await expect(page.getByText("Nguyễn Văn Giảng").first()).toBeVisible();
    await expect(page.getByText(/Manual Present|→/).first()).toBeVisible();
    await page.locator("article button").first().click();
    await expect(page.getByText("Lý do", { exact: false })).toBeVisible();
    await expect(page.getByText("CORRELATION", { exact: false })).toBeVisible();
    await expect(page.getByText(/Trang \d+ \/ \d+/)).toBeVisible();
  });

  test("TC-AC-19-013: lecturer manual correction visible in academic admin audit log", async ({
    page,
  }) => {
    await loginViaApi(
      page,
      LECTURER_PERSONA.email,
      LECTURER_PERSONA.password,
      `/lecturer/sessions/${SEED_FIXTURE_IDS.openSession}/roster`,
    );

    const editButton = page.getByRole("button", { name: /Chỉnh sửa|Điều chỉnh|Sửa/i }).first();
    if ((await editButton.count()) > 0) {
      await editButton.click();
      const dialog = page.getByRole("dialog");
      if ((await dialog.count()) > 0) {
        await page.getByLabel(/Lý do/i).fill("Playwright regression correction");
        await page.getByRole("button", { name: /Xác nhận|Lưu/i }).click();
        await expect(page.getByText(/Có mặt \(thủ công\)|Manual Present/i).first()).toBeVisible({
          timeout: 10_000,
        });
      }
    }

    await loginViaApi(
      page,
      ACADEMIC_ADMIN_SEED_EMAIL,
      LECTURER_PERSONA.password,
      "/audit/logs?actionType=manual_update&from=2026-07-01",
    );

    await expect(page.locator("article").first()).toBeVisible();
    await page.locator("article button").first().click();
    await expect(page.getByText("Lý do", { exact: false })).toBeVisible();
    await expect(page.getByText(/→/).first()).toBeVisible();
  });

  test("TC-AC-16-012: student blocked from institution report and export", async ({ page }) => {
    await page.setViewportSize(STUDENT_PERSONA.viewport);
    await loginViaApi(page, STUDENT_PERSONA.email, STUDENT_PERSONA.password, "/reports/attendance");

    await expect(page.getByText("Không có quyền truy cập")).toBeVisible();
    await expect(page.getByRole("table")).toHaveCount(0);
    await expect(page.getByRole("button", { name: "Xuất CSV" })).toHaveCount(0);

    const loginRes = await page.request.post(`${API_BASE_URL}/auth/login`, {
      data: { email: STUDENT_PERSONA.email, password: STUDENT_PERSONA.password },
    });
    const token = (await loginRes.json()).data?.accessToken as string;
    const exportRes = await page.request.post(`${API_BASE_URL}/exports/attendance`, {
      headers: {
        Authorization: `Bearer ${token}`,
        "Idempotency-Key": `pw-auditor-slice-student-${Date.now()}`,
        "Content-Type": "application/json",
      },
      data: { format: "csv", filters: { termId: SEED_TERM_ID } },
    });
    expect(exportRes.status()).toBe(403);
  });

  test("TC-AC-16-013: lecturer denied for tampered out-of-scope section export", async ({
    page,
  }) => {
    await loginViaApi(page, LECTURER_PERSONA.email, LECTURER_PERSONA.password, "/reports/attendance");

    const sectionOptions = await page
      .getByLabel("Lọc theo lớp học phần")
      .locator("option")
      .allTextContents();
    expect(sectionOptions).toContain("SE101-01");
    expect(sectionOptions.some((label) => label.includes("SE101-02"))).toBe(false);

    await page.goto(
      `${WEB_BASE_URL}/reports/attendance?classSectionId=${OUT_OF_SCOPE_SECTION_ID}&termId=${SEED_TERM_ID}`,
    );
    await expect(page.getByText("Ngoài phạm vi được phép")).toBeVisible();
    await expect(page.getByRole("table")).toHaveCount(0);
    await expect(page.getByRole("button", { name: "Xuất CSV" })).toHaveCount(0);

    const loginRes = await page.request.post(`${API_BASE_URL}/auth/login`, {
      data: { email: LECTURER_PERSONA.email, password: LECTURER_PERSONA.password },
    });
    const token = (await loginRes.json()).data?.accessToken as string;
    const exportRes = await page.request.post(`${API_BASE_URL}/exports/attendance`, {
      headers: {
        Authorization: `Bearer ${token}`,
        "Idempotency-Key": `pw-auditor-slice-oos-${Date.now()}`,
        "Content-Type": "application/json",
      },
      data: {
        format: "csv",
        filters: { termId: SEED_TERM_ID, classSectionId: OUT_OF_SCOPE_SECTION_ID },
      },
    });
    expect(exportRes.status()).toBe(403);
  });
});
