/** Vietnamese report UI copy — FR-12 / FR-13 / AC-12 / AC-13 / NFR-17 */
export const reportCopy = {
  pageTitle: "Báo cáo điểm danh",
  adminPageTitle: "Báo cáo quản trị",
  adminPageDescription: "Báo cáo chuyên cần toàn trường theo bộ lọc",
  exportTitle: "Xuất CSV",
  exportDescription: "Xuất dữ liệu điểm danh theo bộ lọc",
  exportDenied: "Chỉ phòng đào tạo mới có quyền xuất dữ liệu",
  filterClass: "Lớp",
  filterSubject: "Môn học",
  filterFromDate: "Từ ngày",
  filterToDate: "Đến ngày",
  filterApply: "Áp dụng",
  filterClear: "Xóa bộ lọc",
  filterPrompt: "Chọn bộ lọc và nhấn Áp dụng",
  filterAllClasses: "Tất cả",
  emptyResults: "Không có dữ liệu trong khoảng thời gian đã chọn",
  loadError: "Không thể tải báo cáo",
  loadErrorDetail: "Đã xảy ra lỗi khi tải dữ liệu.",
  retry: "Thử lại",
  exportFailed: "Xuất thất bại",
  exportFailedDetail: "Không thể tạo tệp xuất. Vui lòng thử lại.",
  exportButton: "Xuất CSV",
  exportProgress: "Đang tạo tệp…",
  exportSuccess: "Đã tải xuống",
  summaryTotalSessions: "Tổng buổi",
  summaryAvgAttendance: "TB có mặt",
  summaryTotalAbsent: "Tổng vắng",
  summaryTotalExcused: "Tổng vắng có phép",
  colDate: "Ngày",
  colClass: "Lớp",
  colSubject: "Môn",
  colAttendanceRate: "Tỷ lệ có mặt",
  colPresent: "Có mặt",
  colAbsent: "Vắng",
  colExcused: "Vắng có phép",
  colStudentId: "MSSV",
  colStudentName: "Họ tên",
  colAttendanceRateStudent: "Tỷ lệ có mặt",
  colSessionDetail: "Chi tiết",
  pageDescription: "Báo cáo chuyên cần theo lớp và môn được phân công",
  sessionReportTitle: "Báo cáo buổi học",
  sessionReportBack: "Quay lại báo cáo",
  reportAccessDenied: "Bạn không có quyền xem báo cáo này",
  viewSessionReport: "Xem chi tiết",
} as const;
