/** Vietnamese copy for admin user management — FR-01 / AC-01 */
export const userCopy = {
  pageTitle: "Người dùng",
  pageDescription: "Quản lý tài khoản sinh viên, giảng viên và quản trị",
  createButton: "Thêm người dùng",
  createTitle: "Thêm người dùng mới",
  editTitle: "Chỉnh sửa người dùng",
  emptyTitle: "Chưa có người dùng",
  emptyDescription: "Thêm người dùng đầu tiên để bắt đầu quản lý tài khoản.",
  loadError: "Không thể tải danh sách người dùng",
  loadErrorDetail: "Vui lòng thử lại sau.",
  retry: "Thử lại",
  searchPlaceholder: "Tìm theo mã hoặc email…",
  filterRole: "Vai trò",
  filterActive: "Trạng thái",
  filterAllRoles: "Tất cả vai trò",
  filterAllStatuses: "Tất cả trạng thái",
  filterActiveOnly: "Đang hoạt động",
  filterInactiveOnly: "Đã vô hiệu hóa",
  colInstitutionalId: "Mã SV / Mã cán bộ",
  colDisplayName: "Họ và tên",
  colEmail: "Email",
  colRole: "Vai trò",
  colActive: "Trạng thái",
  colActions: "Thao tác",
  activeBadge: "Đang hoạt động",
  inactiveBadge: "Đã vô hiệu hóa",
  editAction: "Chỉnh sửa",
  deactivateAction: "Vô hiệu hóa",
  loadMore: "Tải thêm",
  loadingMore: "Đang tải…",
  lastUpdated: "Cập nhật lúc",
  saveSuccess: "Đã lưu thành công",
  createSuccess: "Đã tạo tài khoản thành công",
  deactivateSuccess: "Đã vô hiệu hóa tài khoản",
  fieldInstitutionalId: "Mã SV / Mã cán bộ",
  fieldDisplayName: "Họ và tên",
  fieldEmail: "Email",
  fieldPassword: "Mật khẩu",
  fieldRole: "Vai trò",
  saveButton: "Lưu",
  cancelButton: "Hủy",
  adminRoleConfirmTitle: "Cấp quyền quản trị?",
  adminRoleConfirmDescription:
    "Cấp quyền quản trị cho tài khoản này? Người dùng sẽ có toàn quyền quản lý hệ thống.",
  adminRoleConfirmButton: "Xác nhận",
  deactivateConfirmTitle: "Vô hiệu hóa tài khoản?",
  deactivateConfirmDescription:
    "Người dùng sẽ không thể đăng nhập sau khi vô hiệu hóa. Phiên đăng nhập hiện tại sẽ bị thu hồi.",
  deactivateConfirmButton: "Vô hiệu hóa",
  passwordHint: "Tối thiểu 8 ký tự",
  userNotFound: "Không tìm thấy người dùng",
  accessDenied: "Bạn không có quyền thực hiện thao tác này",
} as const;
